briannesbitt/Carbon

- tests/ConstructTest.php
- tests/TestFixture.php
Replace https://github.com/briannesbitt/Carbon/pull/211
> Update some tests

- src/Carbon/Lang/de.php
Thanks for adding diffForHuman translation support #32.
Here is a localized file for German language (from a native).
> added German translation files to localized branch

- src/Carbon/Lang/it.php
> italian translation

- src/Carbon/Lang/es.php
- src/Carbon/Lang/fr.php
- tests/LocalizationTest.php
Spanish translation for Carbon
> es (spanish) translation for localised branch

- src/Carbon/Lang/tr.php
- tests/LocalizationTest.php
> Turkish translation

- src/Carbon/Lang/nl.php
Do you also want me to create the tests?
> Dutch translation

- src/Carbon/Lang/pt_BR.php
New Brazilian Portuguese localization to `localized` branch.
> Added Brazilian Portuguese localization

- src/Carbon/Lang/da.php
- tests/LocalizationTest.php
> Add danish translation

- src/Carbon/Lang/ko.php
Korean... hope to see master soon. Thanks for the awesome package.
> Korean translation added. Korean does not have plural

- src/Carbon/Lang/zh.php
Add zh language from laravel-date project
> zh language

- src/Carbon/Lang/zh-TW.php
Add zh-TW language from laravel-date project
> zh-TW language

- src/Carbon/Lang/vi.php
Add vi language from laravel-date project
> vi language

- src/Carbon/Lang/uk.php
Add uk language from laravel-date project
> uk language

- src/Carbon/Lang/th.php
Add th language from laravel-date project
> th language

- src/Carbon/Lang/sv.php
Add sv language from laravel-date project
> sv language

- src/Carbon/Lang/sr.php
Add sr language from laravel-date project
> sr language

- src/Carbon/Lang/sl.php
Add sl language from laravel-date project.
> sl language

- src/Carbon/Lang/sk.php
Add sk language from laravel-date project
> sk language

- src/Carbon/Lang/ru.php
Add ru language from laravel-date project
> ru language

- src/Carbon/Lang/ro.php
Add ro language from laravel-date project
> ro language

- src/Carbon/Lang/pt.php
Add pt language from laravel-date project
> pt language

- src/Carbon/Lang/pl.php
Add pl language from laravel-date project
> pl language

- src/Carbon/Lang/no.php
Add no language from laravel-date project
> no language

- src/Carbon/Lang/ja.php
Add ja language from laravel-date project
> ja language

- src/Carbon/Lang/id.php
Add id language from laravel-date project
> id language

- src/Carbon/Lang/hu.php
Add hu language from laravel-date project
> hu language

- src/Carbon/Lang/hr.php
Add hr language from laravel-date project
> hr language

- src/Carbon/Lang/fi.php
Add fi language from laravel-date project
> fi language

- src/Carbon/Lang/eu
Add eu language from laravel-date project
> eu language

- src/Carbon/Lang/eo.php
Add eo language from laravel-date project
> eo language

- src/Carbon/Lang/el.php
Add el language from laravel-dat project
> el language

- src/Carbon/Carbon.php
- tests/DiffTest.php
Following the PR by @m4tthumphrey i think it should be handy to also have a filterered diff by hours.
> Added function diffInHoursFiltered to filter a Date period by hours

- src/Carbon/Lang/fa.php
- tests/LocalizationTest.php
Added translations for fa (Farsi/Persian) language.
> fa language

- src/Carbon/Lang/az.php
Import az language from laravel-date by @The-Hasanov
> Add az language

- src/Carbon/Carbon.php
> Fix: Remove unused import

- src/Carbon/Lang/lt.php
> Updated LT translation

- src/Carbon/Carbon.php
- src/Carbon/CarbonInterval.php
> Fix: Add missing and fix inconsistent docblock annotations

- src/Carbon/Lang/ms.php
Added translations for ms (Malay) language.
> Add Malay language

- src/Carbon/Lang/bn.php
I have added Bengali translation. Could you please accept the pull request?
> added bangla transalation

- .gitattributes
Follow guidelines to clean up dist packages
http://www.sitepoint.com/mastering-composer-tips-tricks/#making-your-composer-project-lighter
> Exlude /tests for dist package

- src/Carbon/Lang/sq.php
Added Albanian locale for `diffForHumans()`.
> Add Albanian (sq) locale

- src/Carbon/Carbon.php
> Change "occurence" to "occurrence" in Carbon.php

- tests/CarbonIntervalForHumansTest.php
Greek unit test added to CarbonIntervalForHumansTest.php.
Thank you.
> Greek unit test added

- tests/CarbonIntervalForHumansTest.php
Unit test added to cover Danish language pack to CarbonIntervalForHumansTest.php.
Thank you.
> Added Danish unit test for CarbonIntervalForHumansTest.php

- src/Carbon/Carbon.php
- tests/ComparisonTest.php
Add closest & farthest methods
> Add closest function

- src/Carbon/Carbon.php
- src/Carbon/CarbonInterval.php
Use stricter comparisons when possible
> Stricter comparisons

- src/Carbon/Carbon.php
> Useless else

- src/Carbon/Carbon.php
> Fix some docblocks

- .gitattributes
> Do not export .editorconfig

- composer.json
Add support section in composer.json
> Add support section in composer.json

- src/Carbon/Carbon.php
> Fix another docblock

- src/Carbon/Carbon.php
> Use snake cased variable name

- .php_cs
> Excluded PSR0 fix

- src/Carbon/Carbon.php
- src/Carbon/CarbonInterval.php
> Remove usless brackets

- .php_cs
- .styleci.yml
- src/Carbon/CarbonInterval.php
> Add the cast fixer

- .editorconfig
Handle yaml files in editorconfig
> Handle yaml files in editorconfig

- .travis.yml
Enable Codecov.io code coverage
> Enable Codecov.io code coverage

- tests/AbstractTestCase.php
Change instantiation in `\Tests\AbstractTestCase::wrapWithTestNow`
> Change instantiation in \Tests\AbstractTestCase::wrapWithTestNow

- tests/Carbon/CreateTest.php
- tests/CarbonInterval/ConstructTest.php
- tests/CarbonInterval/GettersTest.php
> Change exceptions tests

- .php_cs
- .styleci.yml
- tests/CarbonInterval/ForHumansTest.php
At the moment equals are unaligned, let's keep it this way
Also remove whitespacy lines
> Unalign equals

- src/Carbon/Carbon.php
- src/Carbon/CarbonInterval.php
Fix class docblocks to respect `phpdoc_scalar`
> Fix class docblocks

- src/Carbon/Carbon.php
Simplify calls to parent functions
> Simplify calls to parent functions

- .php_cs
- .styleci.yml
> Remove unused imports

- readme.md
Taken from https://codecov.io/github/briannesbitt/Carbon/features/badges
> Add codecov.io badge for master branch

- src/Carbon/Carbon.php
Avoid calling __set many times
> Avoid calling __set many times

- src/Carbon/Carbon.php
> Avoid calling many __set

- src/Carbon/Carbon.php
- src/Carbon/CarbonInterval.php
The updates to StyleCI are now live in production. Here's a patch to get you passing again. ;)
> Fixed phpdoc following StyleCI update

- src/Carbon/Lang/ka.php
- tests/Localization/KaTest.php
Added Georgian (ka) localization. Also included unit tests
> Added Georgian (ka) localization

- src/Carbon/Carbon.php
- src/Carbon/CarbonInterval.php
- tests/Carbon/ExpressiveComparisonTest.php
I ended up pulling down another copy and making the additions instead of working on top of #446
> Allow for more expressive comparisons

- tests/Carbon/ConstructTest.php
- tests/Carbon/CreateFromDateTest.php
- tests/Carbon/CreateFromFormatTest.php
- tests/Carbon/CreateFromTimeTest.php
- tests/Carbon/CreateFromTimestampTest.php
- tests/Carbon/CreateTest.php
- tests/Carbon/InstanceTest.php
- tests/Carbon/NowAndOtherStaticHelpersTest.php
- tests/Carbon/SettersTest.php
- tests/Carbon/StringsTest.php
And avoid to use FQN class names in code.
> Import namespaces

- src/Carbon/Carbon.php
Ensure all arrays containing +2 elements are multi-lines
> Ensure all arrays containing +2 elements are multi-lines

- src/Carbon/Lang/nl.php
- tests/Localization/NlTest.php
Same reason as c9e9c256211f0a247daaec9b9eb19a6f7d398790
> Fix Dutch translation for years

- tests/Carbon/ComparisonTest.php
- tests/Carbon/CreateFromFormatTest.php
- tests/Carbon/CreateTest.php
- tests/Carbon/FluidSettersTest.php
- tests/Carbon/SettersTest.php
- tests/Carbon/StartEndOfTest.php
We have `\Tests\AbstractTestCase::assertInstanceOfCarbon` so let's use it.
> Use assertInstanceOfCarbon

- src/Carbon/Carbon.php
- src/Carbon/CarbonInterval.php
> Add FQN in doblocks

- src/Carbon/Lang/hy.php
- tests/Localization/HyTest.php
- tests/Localization/NlTest.php
Fix some code syles issues introduced in d1a50b4b06ebbecb1c74c810c65e14a3f6660de3
> Fix some codestyles issues

- src/Carbon/CarbonInterval.php
- tests/CarbonInterval/SpecTest.php
Fixes #525
New version of https://github.com/briannesbitt/Carbon/pull/526 that removes updates to `composer.json`
> Get spec_interval string from CarbonInterval

- tests/CarbonInterval/GettersTest.php
- tests/CarbonInterval/SettersTest.php
> Change variable name

- .php_cs
- .styleci.yml
- src/Carbon/Carbon.php
- src/Carbon/CarbonInterval.php
> Use single quotes

- src/Carbon/Carbon.php
- src/Carbon/CarbonInterval.php
> Also use FQN excpeptions

- src/Carbon/CarbonInterval.php
> Tweak \Carbon\CarbonInterval::add

- .gitattributes
Add * text=auto to .gitattributes
> Add * text=auto to .gitattributes

- .php_cs
> Also import namespaces in .php_cs

- tests/Carbon/IssetTest.php
* Sort properties
* Add untested properties (local, micro, utc, weekOfMonth, weekOfYear)
* Consider each properties as a single test
> Isset tests

- tests/Carbon/ComparisonTest.php
- tests/Carbon/SettersTest.php
> Fix some EOL

- src/Carbon/Carbon.php
- tests/Carbon/AddTest.php
> Add- or sub- quarters

- src/Carbon/Lang/gl.php
- tests/Localization/GlTest.php
Hi... I have done translations for adding Galician language.
> Add Galician language

- src/Carbon/Lang/hu.php
- tests/Localization/HuTest.php
... after I realised that actually I can use second_before, second_ago, etc keys.
Reading the original source code can be really useful!
Also, unit test added for Hungarian language
> Hungarian translation improved A LOT

- .travis.yml
> More travis tests

- src/Carbon/Carbon.php
- tests/Carbon/CreateTest.php
This PR makes the following possible:
- create a date with a negative year
- create a date with 5 digit-long dates (-10000 / +10000)
> Handles negative and +4 digit-long years.

- src/Carbon/Lang/lt.php
> Fix mistype

- src/Carbon/Carbon.php
Remove duplicate last relative keyword
And sort them to avoid noise when adding new ones.
> Remove duplicate last relative keyword

- .php_cs
- .styleci.yml
- tests/Carbon/ComparisonTest.php
- tests/Carbon/SettersTest.php
- tests/CarbonInterval/ForHumansTest.php
> Minor CS adjustments

- tests/Localization/LtTest.php
Updated unit test for Lithuanian language.
> Update Lithuanian test

- tests/Carbon/SettersTest.php
Add more tests for `setTimeFromTimeString`
> Add more tests for setTimeFromTimeString

- src/Carbon/Carbon.php
- tests/Carbon/StartEndOfTest.php
Start- and end- of quarter functions
> Start- and end- of quarter functions

- tests/Carbon/LocalizationTest.php
Use a data provider for `testSetLocaleWithMalformedLocale`
> Use a data provider for testSetLocaleWithMalformedLocale

- tests/Carbon/LocalizationTest.php
> Add missing ka locale test

- .gitattributes
No need to export `CONTRIBUTING.md`
> No need to export CONTRIBUTING.md

- src/Carbon/Carbon.php
Simplify regex in` \Carbon\Carbon::hasRelativeKeywords`
> Simplify regex

- src/Carbon/Carbon.php
Function sets the last day of the week.
> fixes docblock mistype

- src/Carbon/Carbon.php
- tests/Carbon/CreateFromFormatTest.php
Fix issue https://github.com/briannesbitt/Carbon/issues/628 from @tomgrenville
> Retrieve last errors from parent

- .travis.yml
Cache packages and use --prefer-dist
---
See https://github.com/composer/composer/issues/4884#issuecomment-195229989
> Cache packages and use --prefer-dist

- readme.md
> Readme: climb version

- src/Carbon/Carbon.php
Clean up `\Carbon\Carbon::startOfCentury`
> Clean up \Carbon\Carbon::startOfCentury

- src/Carbon/Carbon.php
- tests/Carbon/LocalizationTest.php
> Tweak setLocale

- tests/Carbon/AddTest.php
> Fix 2 typos

- src/Carbon/Carbon.php
Use consistant variable name with camelcase
> Use consistant variable name

- .codecov.yml
- .gitattributes
> Mute codecov PR comments

- src/Carbon/Lang/pt_BR.php
- tests/Localization/PtBrTest.php
- tests/Localization/PtTest.php
Update pt_BR translations
Include commit from @swalker2
---
Closes #711
> Update PT(_BR) translation and tests

- tests/Carbon/AddTest.php
Fix `\Tests\Carbon\AddTest::testSubQuarterNegative`
> Urgent FIX : Failing test \Tests\Carbon\AddTest::testSubQuarterNegative

- .editorconfig
- composer.json
Ensure composer.json use 4 spaces for indentation
> Ensure composer.json use 4 spaces

- .travis.yml
Update Travis Codecov directive: only call remote bash
> Update Travis Codecov directive

- src/Carbon/Carbon.php
Stay consistant and use `static::` keyword
> Use static:: keyword

- tests/CarbonInterval/SpecTest.php
Fix header, CS and remove useless import
> CS : header, fixes and remove useless import

- tests/Carbon/ComparisonTest.php
Rename variable in lowercase, and stay consistant with naming conventions.
> Rename variable in lowercase

- src/Carbon/Carbon.php
- tests/Carbon/AddTest.php
> Add- or sub- centuries

- src/Carbon/Carbon.php
- tests/Carbon/CreateFromTimeTest.php
Consider testNow with create.
Also factorize calls to date.
---
Fix https://github.com/briannesbitt/Carbon/issues/291
> Consider testNow with create

- tests/Localization/HuTest.php
- tests/Localization/LtTest.php
- tests/Localization/PtBrTest.php
> Fix more interval tests

- src/Carbon/Carbon.php
- tests/Carbon/IsTest.php
Return boolean if the date is in this current year.
> Add isCurrentYear, isCurrentMonth, isSameYear, isSameMonth methods

- .php_cs
Import `\Symfony\CS\FixerInterface`
> Import \Symfony\CS\FixerInterface

- src/Carbon/Carbon.php
Simplify `\Carbon\Carbon::createSafe`
> Simplify createSafe

- tests/Carbon/CreateSafeTest.php
Add code covergae for `\Carbon\Exceptions\InvalidDateException`
> Add code covergae for \Carbon\Exceptions\InvalidDateException

- composer.json
> Add Composer scripts

- src/Carbon/Exceptions/InvalidDateException.php
Fix `\Carbon\Exceptions\InvalidDateException`
---
**Note:**
Not sure there should be setters either @briannesbitt ? I feel like just settings the properties in the constructor would be fine.
> Fix \Carbon\Exceptions\InvalidDateException

- src/Carbon/Exceptions/InvalidDateException.php
> Remove exception setters

- src/Carbon/Carbon.php
> Directly call parent function

- src/Carbon/Carbon.php
Factorize previous- and next- week- or weekend day
> Factorize previous- and next- week- or weekend day

- tests/Carbon/SettersTest.php
Use proper `@expectedException` and `@expectedExceptionMessage` assertions
> Use proper expectedException and expectedExceptionMessage assertions

- src/Carbon/Carbon.php
- tests/Carbon/DayOfWeekModifiersTest.php
Fix falsy start/endOfWeek.
---
closes #735
> Fix falsy start/endOfWeek

- src/Carbon/Lang/cs.php
- src/Carbon/Lang/da.php
- src/Carbon/Lang/de.php
- src/Carbon/Lang/el.php
- src/Carbon/Lang/en.php
- src/Carbon/Lang/eo.php
- src/Carbon/Lang/es.php
- src/Carbon/Lang/eu.php
- src/Carbon/Lang/fa.php
- src/Carbon/Lang/fi.php
- src/Carbon/Lang/fo.php
- src/Carbon/Lang/fr.php
- src/Carbon/Lang/he.php
- src/Carbon/Lang/hr.php
- src/Carbon/Lang/hu.php
- src/Carbon/Lang/hy.php
- src/Carbon/Lang/id.php
- src/Carbon/Lang/it.php
- src/Carbon/Lang/ja.php
- src/Carbon/Lang/ka.php
- src/Carbon/Lang/ko.php
- src/Carbon/Lang/lv.php
- src/Carbon/Lang/ms.php
- src/Carbon/Lang/nl.php
- src/Carbon/Lang/no.php
- src/Carbon/Lang/pl.php
Remove useless translation files comments
> Remove useless translation files comments

- tests/Localization/EnTest.php
- tests/Localization/FrTest.php
- tests/Localization/HyTest.php
- tests/Localization/NlTest.php
Ensure all localizations tests use a non-DST date
> Ensure all localizations tests use a non-DST date

- src/Carbon/Carbon.php
> Directly call getOffset

- readme.md
> Add PHP-Eye badge

- src/Carbon/Carbon.php
> Fix some typos

- src/Carbon/Lang/ua.php
- tests/Localization/UaTest.php
Add ukraine language file(ua.php) and unit test for this language
> Add Ukraine language

- src/Carbon/Carbon.php
> Fix function case.

- src/Carbon/Lang/km.php
- tests/Localization/KmTest.php
Hello. This is a commit of adding Khmer language (km) support. Please kindly merge this.
Thanks.
> Add Khmer language support

- src/Carbon/Carbon.php
Use constants for quarter calculations.
> Use constants for quarter calculations.

- .travis.yml
> Also test PHP 7.1 with Travis

- .travis.yml
Fix Travis builds for HHVM and PHP 7.1.
> [WIP] Fix Travis builds for HHVM and PHP 7.1.

- src/Carbon/Carbon.php
Directly call $this->setTimestamp
> Directly call $this->setTimestamp

- .travis.yml
- tests/Carbon/GettersTest.php
- tests/Carbon/IsTest.php
> Make PHP 7.1 tests pass.

- tests/Carbon/GettersTest.php
- tests/Carbon/IsTest.php
Fix PHP 7.1 tests
---
PIng @briannesbitt
> Fix PHP 7.1 tests

- composer.json
> Always sort PHP dependencies

- composer.json
Use new Composer OR syntaxt : `||`
> Use new Composer OR syntax

- tests/Carbon/ModifyTest.php
> Add missing namespace

- tests/Localization/UkTest.php
> Use wrapWithNonDstDate

- src/Carbon/Carbon.php
- tests/Carbon/SerializationTest.php
Add `serialize` and `fromSerialized` functions
---
Related to #599
> Add serialize function

- .gitignore
- phpunit.xml.dist
And also ignore overiden `phpunit.xml`
> PHPunit : respect .editorconfig

- .travis.yml
> Enable codecov for PHP 7.1

- composer.json
> Prepare for release 1.22

- src/Carbon/Carbon.php
- tests/Carbon/CreateFromFormatTest.php
Let extended classes access lastErrors
---
Closes https://github.com/briannesbitt/Carbon/issues/852
> Let extended classes access lastErrors

- .travis.yml
Cleanup .travis.yml for phpstan
> Cleanup .travis.yml for phpstan

- readme.md
PHPStan totally deserves a badge - thx again @ondrejmirtes
> PHPStan totally deserves a badge - thx @ondrejmirtes

- tests/CarbonInterval/SpecTest.php
> Use stricter assertions.

- tests/Carbon/GettersTest.php
> Fix quarter tests.

- src/Carbon/Lang/el.php
https://el.wiktionary.org/wiki/%CF%80%CF%81%CE%B9%CE%BD
https://el.wiktionary.org/wiki/%CE%B1%CF%80%CF%8C
> typos in greek language

- src/Carbon/CarbonInterval.php
> array_push() to array[] =

- src/Carbon/Carbon.php
"secondsUntilEndOfDay" function 's old comment is 'The number of seconds
until 23:23:59'; It should be 'The number of seconds until 23:59:59';
> comment is error;

- .travis.yml
- check.php
Add check command, TravisCI settings and Slack notification.
Fail the documentation build if new undocumented methods are added.
> Documentation checking

- src/Carbon/Lang/az.php
- tests/Localization/AzTest.php
```öncə``` isn't Azeri but Turkish word.
> Minor fix to Azerbaijani localization

- docs/index.html
- docs/index.src.html
Documentation to go along with #988.
> Document createFromTimestampMs method.

- tests/Carbon/SerializationTest.php
Add more serialization tests
---
Fix #894
> Add more serialization tests (Fix issue #894)

- src/Carbon/Carbon.php
Change the word `form` to `from` in method comments
> Fix typo in fromSerialized() method comments

- docs/index.src.html
Add docs for Carbon::setUtf8 (didn't bother to generate ... wait for ……#1100 )
> Add docs for Carbon::setUtf8

- src/Carbon/Lang/sk.php
> Fix Slovak language - Add declensions

- src/Carbon/Lang/mn.php
Now, uses full word for concatenating year, month, day, hour, minute and seconds.
> Improved translation

- src/Carbon/Lang/dv_MV.php
- tests/Carbon/StringsTest.php
- tests/Localization/DvMvTest.php
Added support for dv_MV (Divehi / Maldives) locale
> Locale dv mv

- tests/Localization/SkTest.php
Created based on sk.php file on the Master branch
> Fix SkTest.php

- src/Carbon/Lang/sr_Cyrl.php
Script: Cyrl;
Native: Српски;
Regional: sr_RS;
Primary Serbian:
- Latin: src\Carbon\Lang\sr.php
- Cyrillic: src\Carbon\Lang\sr_Cyrl.php (this pull request)
About "sr_*ME.php" files: https://sr.wikipedia.org/sr/%D0%98%D1%98%D0%B5%D0%BA%D0%B0%D0%B2%D1%81%D0%BA%D0%B8_%D0%B8%D0%B7%D0%B3%D0%BE%D0%B2%D0%BE%D1%80
> Add Serbian (Cyrillic) Language

- src/Carbon/Carbon.php
- tests/Carbon/ModifyNearDSTChangeTest.php
- tests/Carbon/ModifyTest.php
> Remove modify and fix diffInSeconds

- src/Carbon/Carbon.php
- tests/Carbon/StringsTest.php
> Provide RFC7231 formating

- src/Carbon/Carbon.php
- tests/Carbon/ExpressiveComparisonTest.php
> Add isLastOfMonth comparison

- src/Carbon/Carbon.php
- tests/Carbon/ArraysTest.php
- tests/Carbon/GettersTest.php
- tests/Carbon/SettersTest.php
- tests/Carbon/StartEndOfTest.php
- toArray(): array
- startOfHour(): Carbon Modify to start of current hour, minutes and seconds become 0
- endOfHour(): Carbon Modify to end of current hour, minutes and seconds become 59
- startOfMinute(): Carbon Modify to start of current minute, seconds become 0
- endOfMinute() : Carbon Modify to end of current minute, seconds become 59
- midDay(): Carbon Modify to midday, default to self::$midDayAt
> Extra helpers

- src/Carbon/Carbon.php
- Allow DateTime and DateTimeInterface in diff and comparison methods
- Rename dt and abs to explicit date and absolute
> Allow DateTime and DateTimeInterface in diff methods

- .travis.yml
- composer.json
- src/Carbon/Carbon.php
... also moved commands from travis to composer file.
> Fix for phpcs to pass

- src/Carbon/Carbon.php
- tests/Carbon/StartEndOfTest.php
Can fix problem like this one: #1187
> Use the native way to get today/yesterday/tomorrow

- .php_cs.dist
- tests/Carbon/CreateFromTimeTest.php
- tests/Carbon/CreateSafeTest.php
- tests/Carbon/DayOfWeekModifiersTest.php
- tests/Carbon/DiffTest.php
- tests/Carbon/ModifyNearDSTChangeTest.php
- tests/Carbon/PhpBug72338Test.php
Reverts briannesbitt/Carbon#1193 (wrong authorship)
> Revert "Unit tests fixes" (wrong authorship)

- readme.md
> Fact check the readme

- readme.md
https://en.wikipedia.org/wiki/Year_2038_problem
> Change example to use Year 2038 problem

- src/Carbon/Carbon.php
- src/Carbon/CarbonInterval.php
- tests/Carbon/DiffTest.php
- tests/CarbonInterval/ConstructTest.php
> Add diffAsCarbonInterval and allow CarbonInterval from diff

- src/Carbon/Carbon.php
- tests/Carbon/IsTest.php
The following methods have been added:
- isSameQuarter
- isCurrentQuarter
- isNextQuarter
- isLastQuarter
resolves #1235
> Added Methods for Quarter

- src/Carbon/Carbon.php
- tests/Carbon/MacroTest.php
(cherry picked from commit a43cd47)
> Always pass $self at its position even if previous arguments miss

- src/Carbon/Lang/oc.php
Locale file language for Occitan language
> Occitan translation

- src/Carbon/CarbonInterval.php
- tests/CarbonInterval/CascadeTest.php
- tests/CarbonInterval/TotalTest.php
Allow custom cascade factors to handle duration strings input and output such as work logging
> Carbon interval cascade

- src/Carbon/Lang/oc.php
- tests/Localization/OcTest.php
> Add occitan language

- phpstan.neon
- phpunit.xml.dist
- src/Carbon/Carbon.php
- src/Carbon/CarbonInterval.php
- src/Carbon/CarbonPeriod.php
- src/Carbon/Lang/en.php
- tests/AbstractTestCase.php
- tests/Carbon/DiffTest.php
- tests/Carbon/IsTest.php
- tests/CarbonInterval/SettersTest.php
- tests/CarbonInterval/ToPeriodTest.php
- tests/CarbonPeriod/AliasTest.php
- tests/CarbonPeriod/CreateTest.php
- tests/CarbonPeriod/FilterTest.php
- tests/CarbonPeriod/Fixtures/CarbonPeriodFactory.php
- tests/CarbonPeriod/Fixtures/FooFilters.php
- tests/CarbonPeriod/Fixtures/Mixin.php
- tests/CarbonPeriod/Fixtures/filters.php
- tests/CarbonPeriod/GettersTest.php
- tests/CarbonPeriod/IteratorTest.php
- tests/CarbonPeriod/MacroTest.php
- tests/CarbonPeriod/SettersTest.php
- tests/CarbonPeriod/ToArrayTest.php
- tests/CarbonPeriod/ToStringTest.php
Alternative of #1257 with no relying on DatePeriod (to complete)
> Carbon period from scratch

- contribute/index.html
- contribute/index.src.html
- docs/index.html
- docs/index.src.html
- generate.php
- history/index.html
- history/index.src.html
- jumbotron.src.html
- Simplify exec/eval documentation system
- Document version 1.30
> Simplify exec/eval documentation system and document version 1.30

- phpdoc.php
- src/Carbon/Carbon.php
- src/Carbon/CarbonImmutable.php
- src/Carbon/CarbonInterface.php
- src/Carbon/CarbonPeriod.php
- src/Carbon/CarbonTimeZone.php
- src/Carbon/Traits/Date.php
- src/Carbon/Traits/Difference.php
- src/Carbon/Traits/Test.php
- tests/Carbon/AddTest.php
- tests/Carbon/ComparisonTest.php
- tests/Carbon/ExpressiveComparisonTest.php
- tests/Carbon/GettersTest.php
- tests/Carbon/RoundTest.php
- tests/Carbon/SettersTest.php
- tests/Carbon/StartEndOfTest.php
- tests/Carbon/SubTest.php
- tests/CarbonImmutable/AddTest.php
- tests/CarbonImmutable/RoundTest.php
- tests/CarbonImmutable/SettersTest.php
- tests/CarbonImmutable/SubTest.php
- tests/CarbonTimeZone/CreateTest.php
- Methods floor/ceil/round
- Methods get/set/add/sub
- Methods isAfter/isBefore/isBetween
- Methods utcOffset/tz/subtract/startOf/endOf
> Add methods for rounding, comparison, get/set and modifiers

- src/Carbon/Lang/pt_BR.php
Carbon::JUST_NOW, Carbon::ONE_DAY_WORDS and Carbon::TWO_DAY_WORDS now works in PT-BR Language
> Update pt_BR Language

- .gitattributes
- composer.json
- phpstan.neon
- phpunit.xml.dist
- src/Carbon/Laravel/ServiceProvider.php
- tests/AbstractTestCase.php
- tests/Laravel/App.php
- tests/Laravel/EventDispatcher.php
- tests/Laravel/ServiceProvider.php
- tests/Laravel/ServiceProviderTest.php
Provide a service to synchronize automatically our locale to the Laravel one if the service is loaded (can be via auto-discover)
> Automate synchronization with Laravel locale

- src/Carbon/Carbon.php
- src/Carbon/Lang/fr.php
- tests/Carbon/LocalizationTest.php
- More precise localeHasShortUnits
- Translate missing french period sentences
>  More precise localeHasShortUnits

- src/Carbon/Lang/oc.php
Line 40 has to be plural, otherwise it's "còp"
> [i18n]Occitan update for #1367

- src/Carbon/Lang/az.php
Added missing translations for the Azerbaijani language.
> Added rest of translations in Azerbaijani.

- src/Carbon/Lang/es.php
This form is more used and commun around the world
> Change before yesterday Spanish translation

- contribute/index.html
- docs/index.html
- history/index.html
- index.html
- template.src.html
Replace to `GitHub` from `Github`
> Fix GitHub Capitalize in docs

- src/Carbon/CarbonInterval.php
- src/Carbon/CarbonTimeZone.php
- src/Carbon/Traits/Date.php
- src/Carbon/Traits/Difference.php
- src/Carbon/Traits/Macro.php
Looking some classes I noticed the class has some errors phpDocs annotations, this PR has the intention to solve this errors.
> Set correctly phpDocs

- src/Carbon/Lang/it.php
- tests/Localization/ItTest.php
(cherry picked from commit 3aad4c9890e40518eee9d4736a571303f1832480)
> Fix IT lang last day translation

- src/Carbon/Translator.php
Just adds the missing docblock for the trans() method.
> Add trans docblock

- src/Carbon/CarbonInterval.php
- tests/AbstractTestCase.php
- tests/CarbonInterval/AddTest.php
- tests/CarbonInterval/TotalTest.php
Fix #1481 total milliseconds/microseconds in intervals
Fix #1482 microseconds in intervals add, instance and create
> Improve milliseconds/microseconds support

- .travis.yml
#1511 Add more PHP versions to Travis runs
>  Test all version that changed PHP date behavior

- .travis.yml
- tests/AbstractTestCase.php
- tests/Carbon/CreateFromTimeStringTest.php
- tests/Carbon/CreateFromTimestampTest.php
- tests/Carbon/CreateSafeTest.php
- tests/Carbon/DiffTest.php
- tests/Carbon/GettersTest.php
- tests/Carbon/InstanceTest.php
- tests/Carbon/IsTest.php
- tests/Carbon/JsonSerializationTest.php
- tests/Carbon/MacroTest.php
- tests/Carbon/PhpBug72338Test.php
- tests/Carbon/StartEndOfTest.php
- tests/CarbonInterval/MacroTest.php
- tests/CarbonPeriod/MacroTest.php
#1511 Add more PHP versions to Travis runs
> Travis patch versions

- src/Carbon/Carbon.php
- src/Carbon/CarbonImmutable.php
- src/Carbon/CarbonInterface.php
- src/Carbon/Traits/Date.php
- src/Carbon/Traits/Difference.php
- src/Carbon/Traits/Units.php
- tests/Carbon/AddTest.php
- tests/Carbon/ModifyTest.php
- tests/CarbonImmutable/AddTest.php
- tests/CarbonImmutable/ModifyTest.php
Added shortcut methods to add, sub or diff milliseconds (milli) that call respective microsecond methods under the hood
> Add methods add/sub/diffIn milliseconds

- docs/index.src.html
> Fix localization docs for v1

- src/Carbon/Lang/tk_TM.php
- tests/Localization/TkTest.php
- tests/Localization/TkTmTest.php
Re-merge with no squash to keep authorship
> Fix #1664 Add ago/from now/before/after translations

- .travis.yml
- bin/upgrade-carbon
- bin/upgrade-carbon.bat
- composer.json
- src/Carbon/Carbon.php
- src/Carbon/Lang/it.php
- src/Carbon/Upgrade.php
- tests/Carbon/IsTest.php
- tests/Localization/ItTest.php
> [1.26] Upgrade script

- .travis.yml
- bin/upgrade-carbon
- bin/upgrade-carbon.bat
- composer.json
- src/Carbon/Upgrade.php
- tests/Carbon/StartEndOfTest.php
> [1.38] Upgrade script

- src/Carbon/CarbonInterface.php
- src/Carbon/Traits/Comparison.php
- src/Carbon/Traits/Creator.php
- src/Carbon/Traits/Date.php
- src/Carbon/Traits/Modifiers.php
- tests/Carbon/DayOfWeekModifiersTest.php
- tests/Carbon/IsTest.php
- tests/Carbon/ModifyTest.php
- tests/CarbonImmutable/IsTest.php
- tests/CarbonImmutable/ModifyTest.php
```php
var_dump(Carbon::parse('2019-06-02 12:23:45')->is('2019')); // true
var_dump(Carbon::parse('2019-06-02 12:23:45')->is('2018')); // false
var_dump(Carbon::parse('2019-06-02 12:23:45')->is('2019-06')); // true
var_dump(Carbon::parse('2019-06-02 12:23:45')->is('06-02')); // true
var_dump(Carbon::parse('2019-06-02 12:23:45')->is('2019-06-02')); // true
var_dump(Carbon::parse('2019-06-02 12:23:45')->is('Sunday')); // true
var_dump(Carbon::parse('2019-06-02 12:23:45')->is('June')); // true
var_dump(Carbon::parse('2019-06-02 12:23:45')->is('12:23')); // true
var_dump(Carbon::parse('2019-06-02 12:23:45')->is('12:23:45')); // true
var_dump(Carbon::parse('2019-06-02 12:23:45')->is('12:23:00')); // false
var_dump(Carbon::parse('2019-06-02 12:23:45')->is('12h')); // true …
```
> Generic methods

- src/Carbon/Laravel/ServiceProvider.php
- tests/Laravel/App.php
Extracted from @barryvdh PR #1777.
> Optimize Laravel booting

- src/Carbon/CarbonInterval.php
- src/Carbon/CarbonPeriod.php
- src/Carbon/Exceptions/NotAPeriodException.php
- tests/CarbonInterval/CloneTest.php
- tests/CarbonPeriod/CloneTest.php
- tests/CarbonPeriod/CreateTest.php
- tests/CarbonPeriod/IterationMethodsTest.php
- make()
- instance()
- copy() / clone()
- forEach()
- map()
> Implement new methods on CarbonPeriod

- src/Carbon/CarbonPeriod.php
- tests/CarbonPeriod/ComparisonTest.php
> Add equalTo method to CarbonPeriod.

- src/Carbon/CarbonInterval.php
- src/Carbon/CarbonPeriod.php
- tests/CarbonInterval/ComparisonTest.php
- tests/CarbonPeriod/ComparisonTest.php
> Add notEqualTo to CarbonInterval and CarbonPeriod

- src/Carbon/CarbonInterval.php
- src/Carbon/Traits/Date.php
- src/Carbon/Traits/Localization.php
- tests/CarbonInterval/AlternativeNumbersTest.php
- tests/Localization/BnBdTest.php
- tests/Localization/BnInTest.php
- tests/Localization/BnTest.php
- tests/Localization/MyMmTest.php
- tests/Localization/MyTest.php
- tests/Localization/OrInTest.php
- tests/Localization/OrTest.php
> Add altNumbers option to forHumans/diffForHumans

- src/Carbon/Traits/Creator.php
- src/Carbon/Traits/Test.php
- tests/Carbon/TestingAidsTest.php
- tests/CarbonImmutable/TestingAidsTest.php
> Fix #1860 Allow Closure in setTestNow()

- contribute/docs/index.src.html
I struggled to find where the docs source is actually located.
> Add the most relevant info on how to contribute to the docs to the top

- phpunit.xml.dist
- src/Carbon/CarbonInterval.php
- src/Carbon/CarbonPeriod.php
- src/Carbon/Traits/Date.php
- src/Carbon/Traits/Mixin.php
- tests/Carbon/GenericMacroTest.php
- tests/CarbonImmutable/GenericMacroTest.php
- tests/CommonTraits/MacroContextNestingTest.php
> #1814 Implement PHP 8 compliant macro syntax

- docs/index.src.html
Clarify the difference between instance macros and static macros and add an example.
> Enhance guide for static macros

- src/Carbon/CarbonInterface.php
- src/Carbon/Factory.php
- src/Carbon/FactoryImmutable.php
- src/Carbon/Traits/Converter.php
- src/Carbon/Traits/Date.php
- tests/Carbon/StringsTest.php
Add `$unitPrecision` parameters to:
- toDateTimeLocalString
- toTimeString
- toDateTimeString
- toIso8601ZuluString
> #356 Add toDateTimeLocalString precision parameter

- src/Carbon/CarbonInterface.php
Fixed bad one + changed date to have at least 1 true example.
Is the documentation generated automaticly ?
> Fixed all greater examples

- phpmd.xml
- src/Carbon/CarbonInterface.php
- src/Carbon/CarbonInterval.php
- tests/CarbonInterval/ForHumansTest.php
Hi. Thanks for your suggestion to submit a PR [here](https://github.com/briannesbitt/Carbon/issues/559#issuecomment-552608654). This is a rough draft and I'm open to feedback. Thanks!
> Add option for rounding in forHumans

- composer.json
- phpmd.xml
- phpstan.neon
- src/Carbon/CarbonInterval.php
- src/Carbon/CarbonPeriod.php
- src/Carbon/Exceptions/NotLocaleAwareException.php
- src/Carbon/Traits/Date.php
- src/Carbon/Traits/Localization.php
- tests/Carbon/IsTest.php
- tests/Carbon/LocalizationTest.php
- tests/CarbonImmutable/IsTest.php
- tests/CarbonImmutable/LocalizationTest.php
- tests/CarbonInterval/ForHumansTest.php
> Use CarbonInterface instead of self for Date trait constant as keys

- src/Carbon/Translator.php
> Speed up resetMessages

- src/Carbon/CarbonInterface.php
- src/Carbon/CarbonInterval.php
- src/Carbon/Traits/Comparison.php
- tests/Carbon/ComparisonTest.php
- tests/CarbonInterval/ComparisonTest.php
Implement #2012 ->betweenIncluded() method on Carbon, CarbonImmutable and CarbonInterval
> Implement #2012 ->betweenIncluded() method

- symfony/index.src.html
Hello,
Just a quick fix on the paths in the doc. :)
> Fix ORM configuration paths

- src/Carbon/Doctrine/DateTimeImmutableType.php
- src/Carbon/Doctrine/DateTimeType.php
Hey,
There was a slight mix-up here :)
> Fix doctrine ORM Carbon type inheritance

- src/Carbon/Traits/Comparison.php
Nothing important but correction is correction :)
> Typo in example of phpdoc

- src/Carbon/CarbonTimeZone.php
- tests/CarbonTimeZone/ConversionsTest.php
Fix #2059 problem with timezone offset
Use data provider for testing multiple cases
> Fix #2059 timezone offset name for not full hour

- src/Carbon/CarbonInterface.php
- src/Carbon/Traits/Creator.php
- tests/Carbon/DiffTest.php
> #2075 Mute fallback parse() error to throw only the original one

- src/Carbon/Traits/Localization.php
- tests/Jenssegers/TranslationUkTest.php
> #2081 Fix Ukrainian parsing

- src/Carbon/Lang/si.php
- tests/Localization/SiLkTest.php
- tests/Localization/SiTest.php
> Fix #2076 Sinhala translations

- src/Carbon/Doctrine/CarbonTypeConverter.php
- tests/Doctrine/CarbonTypesTest.php
> Revert Doctrine default precision change

- composer.json
- docs/index.html
- docs/index.src.html
- index.html
- reference/index.html
- tools/generate.php
> Document 2.36

- src/Carbon/Lang/lt.php
> Fix #2138 Implement standalone months for Lithuanian language

- src/Carbon/CarbonInterval.php
- tests/CarbonInterval/RoundingTest.php
> Fix #2136 Handle negated interval rounding

- src/Carbon/CarbonInterface.php
- src/Carbon/Traits/Creator.php
Align PHPDoc with actual method capacities
> Accept DateTimeInterface in parse()

- src/Carbon/CarbonInterface.php
- src/Carbon/Traits/Converter.php
- tests/Carbon/StringsTest.php
- tests/CarbonImmutable/StringsTest.php
> #2146 Add shortand for DateTimeInterface::RFC3339_EXTENDED

- src/Carbon/Lang/ast.php
- src/Carbon/Lang/ast_ES.php
- tests/Localization/AstEsTest.php
- tests/Localization/AstTest.php
> 🌎 #2150 Fix Asturian plural

- src/Carbon/Factory.php
- tests/Factory/FactoryTest.php
Fix #2177 auto-fill timezone argument in factory methods
> Fix #2177 auto-fill timezone argument in factory methods

- src/Carbon/Lang/lb.php
- tests/Localization/LbLuTest.php
- tests/Localization/LbTest.php
Fix #2187 Luxembourgish translations
> Fix #2187 Luxembourgish translations

- src/Carbon/CarbonInterface.php
- src/Carbon/Traits/Creator.php
> Use constants instead of 3600

- src/Carbon/Traits/Creator.php
- tests/Carbon/CreateFromFormatTest.php
Fix for https://github.com/laravel/framework/issues/34474
Work-around for https://bugs.php.net/bug.php?id=80141
> Allow Carbon::createFromFormat('c')

- src/Carbon/Traits/Options.php
- tests/Carbon/ArraysTest.php
- tests/Carbon/Fixtures/DumpCarbon.php
> Fix #2201 Add date and timezone in debug info only when ready

- readme.md
This avoids issues when rendering markdown on packagist
> Avoid using a self-closing tag in readme

- .gitignore
- src/Carbon/CarbonInterface.php
- src/Carbon/Traits/Date.php
- src/Carbon/Traits/Microtime.php
- tests/Carbon/CreateFromMicrotimeTest.php
> #2199 create from microtime

- src/Carbon/Traits/Comparison.php
- src/Carbon/Traits/Options.php
- tests/Carbon/IsTest.php
> #2198 Add hasFormatWithModifiers() method

- src/Carbon/CarbonPeriod.php
- tests/CarbonPeriod/AliasTest.php
- tests/CarbonPeriod/GettersTest.php
- tests/CarbonPeriod/IteratorTest.php
> #2194 Add readonly public properties to CarbonPeriod

- src/Carbon/Laravel/ServiceProvider.php
- tests/CarbonPeriod/FilterTest.php
- tests/CarbonPeriod/Fixtures/AbstractCarbon.php
- tests/CarbonPeriod/SettersTest.php
- tests/Language/TranslatorTest.php
- tests/Laravel/App.php
- tests/Laravel/ServiceProviderTest.php
> Fix #2209 Cover missed branches

- src/Carbon/Traits/Creator.php
- tests/Carbon/ConstructTest.php
- tests/CarbonImmutable/ConstructTest.php
> Fix #2214 YYYYMMDD support for parse()

- src/Carbon/Lang/oc.php
- tests/Localization/OcFrTest.php
- tests/Localization/OcTest.php
> Fix #2240 fix Occitan ordinal rule

- .github/workflows/tests.yml
- tests/Carbon/ArraysTest.php
- tests/Carbon/Fixtures/DumpCarbon.php
- Install locales for tests on GitHub Actions
- Add catch exception test for __debugInfo
> Install locales for tests on GitHub Actions

- .github/workflows/tests.yml
- composer.json
- src/Carbon/Traits/Date.php
- src/Carbon/Traits/Options.php
- tests/Carbon/IsTest.php
- tests/Carbon/SettersTest.php
- tests/CarbonImmutable/IsTest.php
> Fix utcOffset() with minutes

- src/Carbon/Traits/Rounding.php
- tests/Carbon/RoundTest.php
- tests/CarbonImmutable/RoundTest.php
- tests/CarbonInterval/ForHumansTest.php
Work around month overflow when using rounding methods.
Fix #2268
> Fix rounding with month overflow

- src/Carbon/CarbonPeriod.php
- src/Carbon/Traits/Options.php
- tests/CarbonPeriod/GettersTest.php
> Filter UnknownGetterException from getSettings

- .github/workflows/tests.yml
- composer.json
- phpunit.xml.dist
- Upgrade to PHPUnit 9
- Split style check jobs
> Upgrade to PHPUnit 9

- src/Carbon/Traits/Rounding.php
- tests/Carbon/RoundTest.php
- tests/CarbonImmutable/RoundTest.php
> Use finest overflow detection

- .github/workflows/tests.yml
- tests/Carbon/CreateTest.php
- Add OutOfRangeException type
- Temporary disable PHP 8.1 checking
> Add OutOfRangeException type

- src/Carbon/Lang/ms.php
- tests/Localization/MsMyTest.php
- tests/Localization/MsTest.php
Referring to "Institute of Language and Literature" in Malaysia
00 - 11:59 => Morning (Pagi)
12 - 13:59 => Noon (Tengahari)
14 - 18:59 => Evening (Petang)
19 - 23:59 => Night (Malam)
https://scontent.fkul10-1.fna.fbcdn.net/v/t1.6435-9/91843347_3594870780583864_5094108869806784512_n.jpg?_nc_cat=106&ccb=1-3&_nc_sid=8bfeb9&_nc_ohc=CTyRqXG61m8AX-kqNli&_nc_ht=scontent.fkul10-1.fna&oh=2cf8bf996a64a52bb58d48f9ae215d6f&oe=609A6E7D
> Wrong Translation and Hour range

- src/Carbon/Traits/Difference.php
- tests/Carbon/CreateTest.php
- tests/Carbon/DiffTest.php
> Fix #2308 Compare dates in UTC to get real diff in days and above units

- src/Carbon/Translator.php
> #2322 Fix regular expression to also match numbers in locale 

- src/Carbon/CarbonImmutable.php
- src/Carbon/CarbonInterface.php
- src/Carbon/CarbonPeriod.php
- src/Carbon/Traits/Comparison.php
- tests/CarbonPeriod/GettersTest.php
- tests/CarbonPeriod/RoundingTest.php
- tests/Jenssegers/DateTest.php
> Allow endless periods

- src/Carbon/Lang/et.php
- tests/Localization/EtEeTest.php
- tests/Localization/EtTest.php
Source:
http://www.eki.ee/dict/qs2006/lyhendid.html
> Update et.php - Add abbreviations

- src/Carbon/Traits/Creator.php
- tests/Carbon/CreateStrictTest.php
Resolves https://github.com/briannesbitt/Carbon/issues/2329
> Add instantiation method Carbon::createStrict()

- .github/workflows/tests.yml
- src/Carbon/CarbonImmutable.php
- src/Carbon/CarbonInterface.php
- src/Carbon/CarbonInterval.php
- src/Carbon/CarbonPeriod.php
- src/Carbon/Traits/Comparison.php
- src/Carbon/Traits/Converter.php
- src/Carbon/Traits/Date.php
- src/Carbon/Traits/Difference.php
- src/Carbon/Traits/IntervalStep.php
- src/Carbon/Traits/Modifiers.php
- src/Carbon/Traits/Rounding.php
- src/Carbon/Traits/Units.php
- src/Carbon/Traits/Week.php
Fix PHP 8.1 regression
- Work around PHP bug 81106
- Work around PHP bug 81106
> Add avoidMutation() method to copy an instance only if mutable

- composer.json
- phpunit.xml.dist
- readme.md
- src/Carbon/CarbonInterface.php
- src/Carbon/CarbonInterval.php
- src/Carbon/Lang/bn_BD.php
- src/Carbon/Lang/shn_MM.php
- src/Carbon/Traits/Date.php
- tests/Carbon/GettersTest.php
- tests/CarbonImmutable/GettersTest.php
- tests/CarbonInterval/CreateFromFormatTest.php
Prefer `https` secure scheme over `http` scheme.
> Prefer https secure scheme.

- tests/AbstractTestCaseWithOldNow.php
- tests/CarbonTimeZone/ConversionsTest.php
Directly extend `AbstractTestCaseWithOldNow`
> Directly extend AbstractTestCaseWithOldNow

- tests/Carbon/PhpBug72338Test.php
- tests/CarbonImmutable/PhpBug72338Test.php
> Remove some useless functions

- src/Carbon/Doctrine/CarbonTypeConverter.php
- src/Carbon/Traits/Options.php
Remove some useless conditions
> Remove some useless conditions

- tests/CarbonInterval/ForHumansTest.php
- tests/CarbonPeriod/CreateTest.php
- tests/Jenssegers/TranslationJaTest.php
- tests/Jenssegers/TranslationTaTest.php
Always use stricter string assertions when possible.
> Always use stricter string assertions

- src/Carbon/Traits/Timestamp.php
- tests/CarbonImmutable/CreateFromTimestampTest.php
> Fix #2368 pad left trailing zeros in createFromTimestamp()

- .github/workflows/tests.yml
Fix yml file spacing and formatting.
> Fix yml file spacing and formatting.

- src/Carbon/CarbonInterval.php
- src/Carbon/Traits/Date.php
This PR removes redundant casts.
> Remove redundant casts.

- phpunit.xml.dist
- tests/bootstrap.php
This PR gets rid of the test bootstrap file
> Gets rid of the test bootstrap file

- src/Carbon/Traits/Converter.php
- src/Carbon/Traits/ObjectInitialisation.php
- src/Carbon/Traits/Options.php
- src/Carbon/Traits/Serialization.php
- tests/Carbon/Fixtures/Mixin.php
- tests/CarbonImmutable/Fixtures/Mixin.php
- tests/CarbonInterval/Fixtures/Mixin.php
- tests/Laravel/ServiceProviderTest.php
This PR removes some useless default assignment.
> Remove useless default assignment.

- .github/workflows/tests.yml
- .multi-tester.yml
Stop using soon to be deprecated `--no-suggest` composer flag.
> Stop using --no-suggest flag

- tests/CarbonPeriod/CreateTest.php
- tests/CarbonPeriod/SettersTest.php
- tests/CarbonTimeZone/ConversionsTest.php
- tests/Jenssegers/DateTest.php
This PR enforces the use of stricter assertions
> Use stricter assertions

- .github/workflows/tests.yml
- src/Carbon/Traits/Serialization.php
- tests/Carbon/SerializationTest.php
- tests/CarbonImmutable/SerializationTest.php
> Fix #2299 Add support for msgpack

- .gitattributes
> Ignore some other exports

- .github/workflows/tests.yml
This PR directly uses the codecov action
> Directly use the codecov action

- phpdoc.php
- tests/Carbon/CreateSafeTest.php
- tests/Carbon/InstanceTest.php
- tests/Carbon/LocalizationTest.php
- tests/CarbonImmutable/CreateSafeTest.php
- tests/CarbonImmutable/InstanceTest.php
- tests/CarbonImmutable/LocalizationTest.php
- tests/CarbonTimeZone/ConversionsTest.php
This PR enforces consistency by avoiding FQCN for classes, interfaces and traits which have already been imported.
> Avoid FQCN

- .gitattributes
- .php-cs-fixer.dist.php
- src/Carbon/Lang/be.php
- src/Carbon/Lang/sh.php
- src/Carbon/Traits/Comparison.php
- src/Carbon/Translator.php
- tests/Carbon/SettersTest.php
This PR fixes PHP-CS-Fixer depreciations, detected and displayed when running `composer phpcs` script.
> Fix PHP-CS-Fixer depreciations

- .gitattributes
> Restore PHPStan extension config in package

- tests/AbstractTestCase.php
- tests/Carbon/ArraysTest.php
- tests/Carbon/CreateTest.php
- tests/Carbon/SerializationTest.php
- tests/CarbonImmutable/SerializationTest.php
- tests/CarbonInterval/ToDateIntervalTest.php
- tests/CarbonPeriod/DynamicIntervalTest.php
- tests/CarbonPeriod/MacroTest.php
- tests/CarbonPeriod/ToDatePeriodTest.php
- tests/Language/LanguageTest.php
This PR ensure that the proper tests assertions are used.
> Use proper assertions

- tests/Carbon/ObjectsTest.php
- tests/Cli/InvokerTest.php
- tests/Laravel/Dispatcher.php
- tests/Laravel/ServiceProviderTest.php
Stay consistent and avoid FQCN
> Stay consistent and avoid FQCN

- src/Carbon/Traits/Units.php
- tests/Carbon/AddTest.php
- tests/CarbonImmutable/AddTest.php
> Fix overflow with plural unit

- src/Carbon/Traits/Units.php
> Remove work-around for bug 81106

- src/Carbon/Traits/Difference.php
PHP announced bug 80974 is fixed in PHP version 8.1.0beta3
> Remove work-around for bug 80974

- .gitignore
- .php-cs-fixer.dist.php
- composer.json
Upgrade to `friendsofphp/php-cs-fixer` version to `^3`.
---
This has been made possible by https://github.com/kylekatarnls/multi-tester/pull/8
> Upgrade to friendsofphp/php-cs-fixer ^3.

- build.php
- phpdoc.php
- src/Carbon/CarbonInterval.php
- src/Carbon/CarbonPeriod.php
- src/Carbon/Traits/Creator.php
- src/Carbon/Traits/Difference.php
- src/Carbon/Translator.php
Use null coalescing operator when possible
> Use null coalescing operator when possible

- src/Carbon/Lang/cv.php
- src/Carbon/Lang/nl.php
- src/Carbon/Lang/si.php
- src/Carbon/Lang/uk.php
Add missing `u` regexp modifier
(as the regexp contains unicode characters)
> Add missing u regexp modifier

- phpstan.neon
> Make phpstan analysis pass.

- .php-cs-fixer.dist.php
- src/Carbon/CarbonInterval.php
Add `PHP71Migration` ruleset to `php-cs-fixer`
> Add PHP71Migration ruleset to php-cs-fixer

- .php-cs-fixer.dist.php
- tests/Carbon/InstanceTest.php
- tests/Carbon/RelativeDateStringTest.php
- tests/CarbonImmutable/InstanceTest.php
- tests/CarbonImmutable/RelativeDateStringTest.php
- tests/Jenssegers/TranslationJaTest.php
- tests/Jenssegers/TranslationTaTest.php
- tests/Localization/JaTest.php
This PR enforces tests consistency with some extra rules
> Enforce tests consistency with some extra rules

- src/Carbon/CarbonInterval.php
- src/Carbon/CarbonPeriod.php
- src/Carbon/Lang/be.php
- src/Carbon/Lang/bg.php
- src/Carbon/Lang/bs.php
- src/Carbon/Lang/el.php
- src/Carbon/Lang/fr.php
- src/Carbon/Lang/hr.php
- src/Carbon/Lang/hy.php
- src/Carbon/Lang/it.php
- src/Carbon/Lang/ja.php
- src/Carbon/Lang/ko.php
- src/Carbon/Lang/lb.php
- src/Carbon/Lang/lt.php
- src/Carbon/Lang/mk.php
- src/Carbon/Lang/pl.php
- src/Carbon/Lang/pt.php
- src/Carbon/Lang/ru.php
- src/Carbon/Lang/sr.php
- src/Carbon/Lang/sr_Cyrl.php
- src/Carbon/Lang/sr_Cyrl_ME.php
- src/Carbon/Lang/sr_Latn_ME.php
- src/Carbon/Lang/ug.php
- src/Carbon/Lang/uk.php
- src/Carbon/Lang/zh_Hans.php
- src/Carbon/Lang/zh_Hant.php
- src/Carbon/Traits/Week.php
This PR simplifies switches and uses match when possible.
> [3.x] Simplify switches and use match when possible

- bin/carbon
- phpdoc.php
- src/Carbon/CarbonInterface.php
- src/Carbon/CarbonTimeZone.php
- src/Carbon/Lang/be.php
- src/Carbon/Lang/bg.php
- src/Carbon/Lang/bs.php
- src/Carbon/Lang/ca.php
- src/Carbon/Lang/el.php
- src/Carbon/Lang/es.php
- src/Carbon/Lang/gl.php
- src/Carbon/Lang/hr.php
- src/Carbon/Lang/hu.php
- src/Carbon/Lang/it.php
- src/Carbon/Lang/ja.php
- src/Carbon/Lang/ka.php
- src/Carbon/Lang/lb.php
- src/Carbon/Lang/mk.php
- src/Carbon/Lang/oc.php
- src/Carbon/Lang/pl.php
- src/Carbon/Lang/pt.php
- src/Carbon/Lang/ru.php
- src/Carbon/Lang/sh.php
- src/Carbon/Lang/sl.php
- src/Carbon/Lang/sr.php
- src/Carbon/Lang/sr_Cyrl.php
- src/Carbon/Lang/sr_Cyrl_ME.php
- src/Carbon/Lang/sr_Latn_ME.php
- src/Carbon/Lang/uk.php
> Avoid FQCN and prefer imports

- src/Carbon/PHPStan/Macro.php
- tests/Carbon/AddMonthsTest.php
- tests/Carbon/InstanceTest.php
- tests/Carbon/SettersTest.php
- tests/CarbonImmutable/InstanceTest.php
- tests/CarbonInterval/SettersTest.php
- tests/CarbonPeriod/IteratorTest.php
- tests/CarbonTimeZone/ConversionsTest.php
- tests/Localization/LocalizationTestCase.php
Remove inferred variables declaration as some of those declarations are useless.
> Remove inferred variables declaration

- .php-cs-fixer.dist.php
> Enforce PSR12 code-style

- .php-cs-fixer.dist.php
> Enforce header declaration

- docs/index.src.html
#2378 added the getTimestampMs method, but I found the docs not updated.
This PR adds a description about getTimeStampMs.
> Add description of getTimestampMs()

- .github/workflows/phpstan.yml
- composer.json
- src/Carbon/Lang/gu.php
- tests/Localization/GuInTest.php
- tests/Localization/GuTest.php
> Fix month plural for Gujarati

- src/Carbon/Traits/Creator.php
- src/Carbon/Traits/Date.php
- tests/Carbon/ComparisonTest.php
- tests/Carbon/CreateFromTimeTest.php
- tests/Carbon/CreateTest.php
- tests/Carbon/DiffTest.php
- tests/Carbon/ExpressiveComparisonTest.php
- tests/CarbonImmutable/ComparisonTest.php
- tests/CarbonImmutable/CreateTest.php
- tests/CarbonImmutable/DiffTest.php
- tests/CarbonImmutable/ExpressiveComparisonTest.php
- tests/CarbonTimeZone/CreateTest.php
> Handle setTestNow() with createFromTime() and create()

- src/Carbon/Lang/ms.php
- tests/Localization/MsMyTest.php
- tests/Localization/MsTest.php
> Fix Malay meridiem

- src/Carbon/CarbonInterface.php
- src/Carbon/CarbonInterval.php
- src/Carbon/Traits/Difference.php
- tests/Carbon/DiffTest.php
- tests/CarbonInterval/ForHumansTest.php
> Add skip option in forHumans() and diffForHumans()

- src/Carbon/Lang/pl.php
- tests/CarbonImmutable/LocalizationTest.php
- tests/Localization/PlPlTest.php
- tests/Localization/PlTest.php
> Fix past declensions in Polish

- tests/Carbon/IssetTest.php
- tests/CarbonImmutable/IssetTest.php
Many properties were not tested.
This PR makes sure that most properties are.
> Test more properties

- tests/Carbon/DiffTest.php
- tests/CarbonImmutable/DiffTest.php
- tests/CarbonInterval/CreateFromFormatTest.php
Enforce stricter exceptions tests.
> Make exceptions tests stricter

- composer.json
> Add a composer docs section.

- src/Carbon/AbstractTranslator.php
This PR provides some adjustment for `AbstractTranslator`
> Make AbstractTranslator class actually abstract

- lazy/Carbon/TranslatorStrongType.php
- lazy/Carbon/TranslatorWeakType.php
- src/Carbon/Translator.php
> Move translator definition outside autoload

- .github/workflows/tests.yml
- lazy/Carbon/TranslatorStrongType.php
- lazy/Carbon/TranslatorWeakType.php
- src/Carbon/Translator.php
Fix #2514
original solution author: @andriesreitsma
> Support classmap-authoritative composer option

- build.php
- composer.json
- lazy/Carbon/PHPStan/MacroStrongType.php
- lazy/Carbon/PHPStan/MacroWeakType.php
- phpstan.neon
- phpunit.xml.dist
- src/Carbon/AbstractTranslator.php
- src/Carbon/CarbonInterval.php
- src/Carbon/CarbonPeriod.php
- src/Carbon/PHPStan/AbstractMacro.php
- src/Carbon/PHPStan/Macro.php
- src/Carbon/Traits/Creator.php
- src/Carbon/Traits/Date.php
- src/Carbon/Traits/Localization.php
- src/Carbon/Traits/Mixin.php
- tests/PHPStan/MacroTest.php
> Support PHPStan 1.*

- src/Carbon/Traits/Comparison.php
- tests/Carbon/ComparisonTest.php
> Use date resolution for comparison

- src/Carbon/Traits/Difference.php
- tests/Carbon/DiffTest.php
> Work around PHP day mismatch bug

- .github/workflows/tests.yml
Run coverage with PHP 8.1 instead of 7.4
> Run coverage with PHP 8.1

- build.php
- src/Carbon/CarbonInterval.php
- src/Carbon/Lang/cy.php
- src/Carbon/Traits/Comparison.php
- src/Carbon/Traits/Date.php
- src/Carbon/Traits/Units.php
- tests/CarbonPeriod/MacroTest.php
- tests/Localization/LanguagesCoverageTest.php
Always use strict `in_array` comparison.
> Always use strict in_array comparison.

- src/Carbon/Traits/Date.php
- src/Carbon/Traits/Rounding.php
- tests/Carbon/RoundTest.php
- tests/CarbonInterval/ForHumansTest.php
> Take minimum value for rounding

- src/Carbon/Lang/da.php
- tests/Localization/DaDkTest.php
- tests/Localization/DaGlTest.php
- tests/Localization/DaTest.php
> [Danish] Weekday and month abbreviations + ‘ago’

- src/Carbon/Traits/Localization.php
> Check both old and new interface for Symfony polyfill

- src/Carbon/CarbonTimeZone.php
- tests/CarbonTimeZone/CreateTest.php
> Allow plus prefix for numeric timezone

- .github/workflows/phpcs.yml
- .github/workflows/phpmd.yml
- .github/workflows/phpstan.yml
- .github/workflows/tests.yml
This PR update Github actions versions.
> Update Github actions versions

- src/Carbon/Traits/Difference.php
- src/Carbon/Traits/Localization.php
- tests/Carbon/ComparisonTest.php
This PR removes useless casting
> Remove useless casting

- src/Carbon/AbstractTranslator.php
- src/Carbon/CarbonInterval.php
- src/Carbon/CarbonTimeZone.php
- src/Carbon/Traits/Comparison.php
This PR simplifies some conditions and promote early returns.
> Simplify some conditions

- src/Carbon/CarbonInterval.php
- tests/Carbon/TestingAidsTest.php
> Improve typehint for year of CarbonInterval

- phpdoc.php
- src/Carbon/AbstractTranslator.php
- src/Carbon/CarbonInterval.php
- src/Carbon/CarbonPeriod.php
- src/Carbon/Lang/it.php
- src/Carbon/Traits/Creator.php
- src/Carbon/Traits/Timestamp.php
This PR simplifies some regex.
> Simplify some regex.

- src/Carbon/PHPStan/MacroExtension.php
Solves https://github.com/briannesbitt/Carbon/issues/2634
> Remove forgotten var_dump, solves #2634

- phpstan.neon
- src/Carbon/Traits/Comparison.php
- src/Carbon/Traits/Creator.php
- tests/Carbon/ExpressiveComparisonTest.php
- tests/CarbonImmutable/ExpressiveComparisonTest.php
> Allow comparison with strings

- src/Carbon/CarbonInterval.php
- tests/CarbonInterval/TotalTest.php
> Allow float numbers in cascade factors

- src/Carbon/Traits/Rounding.php
- tests/Carbon/RoundTest.php
> Prevent floor overflow

- src/Carbon/Traits/Rounding.php
- tests/Carbon/RoundTest.php
> Prevent ceil precision loss

- src/Carbon/Lang/lv.php
> Distinguish months and months_standalone in Latvian

- src/Carbon/Traits/Date.php
- tests/Carbon/WeekTest.php
> Fix weekday setter

- .github/workflows/tests.yml
- lazy/Carbon/PHPStan/AbstractMacroBuiltin.php
- lazy/Carbon/PHPStan/AbstractMacroStatic.php
- lazy/Carbon/PHPStan/MacroStrongType.php
- lazy/Carbon/PHPStan/MacroWeakType.php
- src/Carbon/PHPStan/AbstractMacro.php
- tests/PHPStan/Fixture.php
- tests/PHPStan/MacroExtensionTest.php
- tests/PHPStan/MacroTest.php
- tests/PHPStan/bootstrap-non-static.php
- tests/PHPStan/bootstrap.php
> Fix PHPStan macro arguments check

- src/Carbon/PHPStan/AbstractMacro.php
- src/Carbon/PHPStan/MacroExtension.php
- src/Carbon/Traits/Difference.php
- tests/Carbon/DiffTest.php
- tests/PHPStan/MacroTest.php
Algorithm from https://stackoverflow.com/a/74274307
> Improve diffInMonths calculation

- src/Carbon/PHPStan/MacroExtension.php
- src/Carbon/PHPStan/MacroScanner.php
- tests/PHPStan/MacroExtensionTest.php
> Use static reflection to determine whether class is `CarbonInstance`

- src/Carbon/Traits/Date.php
- tests/Carbon/WeekTest.php
- tests/CarbonImmutable/WeekTest.php
> Add get/set DaysFromStartOfWeek methods

- src/Carbon/CarbonInterval.php
- src/Carbon/CarbonPeriod.php
- src/Carbon/Traits/Date.php
- src/Carbon/Traits/MagicParameter.php
- tests/CarbonImmutable/ModifyTest.php
- tests/CarbonInterval/AddTest.php
- tests/CarbonPeriod/AliasTest.php
- tests/CarbonPeriod/CreateTest.php
> Allow named parameters in magic calls

- tests/Carbon/ModifyTest.php
> Add cast test for addRealHours()

- readme.md
🙏 @w3guy
Would you prefer `https://w3guy.com/` as the link?
Please feel free to edit to another URL for image or website.
> Add new sponsor

- src/Carbon/Lang/pl.php
Updated Polish translation for ```just now```.
Closes #2741
> Updated Polish translation

- src/Carbon/Traits/Difference.php
- tests/Carbon/DiffTest.php
> Enforce $skip array type

- src/Carbon/Traits/Comparison.php
- tests/Carbon/GettersTest.php
- tests/CarbonInterval/RoundingTest.php
> Add isLongIsoYear() method

- src/Carbon/Traits/Comparison.php
- tests/CarbonImmutable/IsTest.php
> Fix is() output when giving a month name only

- src/Carbon/CarbonInterval.php
- tests/CarbonInterval/RoundingTest.php
> Handle rounding with cascade factors

- src/Carbon/CarbonPeriod.php
- tests/CarbonPeriod/CreateTest.php
> Use CarbonImmutable when creating CarbonPeriodImmutable

- phpstan.neon
- src/Carbon/Traits/Mixin.php
- tests/Carbon/MacroTest.php
- tests/CarbonImmutable/MacroTest.php
- tests/Fixtures/CarbonTimezoneTrait.php
> Support named arguments for mixins

- src/Carbon/CarbonPeriod.php
Fixes return types for the `CarbonPeriodImmutable` class
> Fix `CarbonPeriod` method signatures

- composer.json
- phpdoc.php
- src/Carbon/FactoryImmutable.php
- tests/Factory/FactoryTest.php
> Implement `Psr\Clock\ClockInterface`

- src/Carbon/Lang/ms.php
- tests/CarbonPeriod/MacroTest.php
- tests/Localization/MsBnTest.php
- tests/Localization/MsMyTest.php
- tests/Localization/MsSgTest.php
- tests/Localization/MsTest.php
> Change before Malay translation to "sebelum"

- phpstan.neon
- src/Carbon/CarbonInterval.php
- src/Carbon/CarbonPeriod.php
- src/Carbon/Traits/IntervalRounding.php
- src/Carbon/Traits/Units.php
- tests/AbstractTestCase.php
- tests/Carbon/ObjectsTest.php
- tests/CarbonImmutable/ObjectsTest.php
- tests/CarbonInterval/ConstructTest.php
- tests/CarbonInterval/FromStringTest.php
- tests/PHPUnit/AssertObjectHasPropertyNoopTrait.php
- tests/PHPUnit/AssertObjectHasPropertyPolyfillTrait.php
- tests/PHPUnit/AssertObjectHasPropertyTrait.php
- tests/bootstrap.php
- Allow float in interval units
- Allow to create/change period interval using milliseconds() or microseconds() methods
> Allow float in interval units

- src/Carbon/CarbonInterval.php
- tests/CarbonInterval/ConstructTest.php
- tests/CarbonInterval/FloatSettersEnabledTest.php
> Handle decimal part from interval unit setters

- src/Carbon/Traits/Serialization.php
$this->timezone and $this->date gets exception
Fix #2850
> FIX: UnknownGetterException error on Serialization.php

- .github/workflows/tests.yml
- phpdoc.php
- src/Carbon/Carbon.php
- src/Carbon/CarbonImmutable.php
- src/Carbon/CarbonInterface.php
- src/Carbon/CarbonInterval.php
- src/Carbon/Traits/Comparison.php
- src/Carbon/Traits/Date.php
- src/Carbon/Traits/Test.php
- tests/AbstractTestCase.php
- tests/Carbon/DiffTest.php
- tests/Carbon/GenericMacroTest.php
- tests/Carbon/IsTest.php
- tests/Carbon/StringsTest.php
- tests/Carbon/TestingAidsTest.php
- tests/CarbonImmutable/DiffTest.php
- tests/CarbonImmutable/GenericMacroTest.php
- tests/CarbonImmutable/IsTest.php
- tests/CarbonImmutable/TestingAidsTest.php
- tests/CarbonInterval/ConstructTest.php
- tests/PHPStan/MacroTest.php
> Consider same "month" only in the same year

- src/Carbon/Traits/Creator.php
- tests/Jenssegers/DateTest.php
> Allow integer in createFromFormat()

- src/Carbon/CarbonPeriod.php
- src/Carbon/Traits/Converter.php
- tests/CarbonPeriod/CreateTest.php
> Fallback to default parameters if period construction fails

- .github/workflows/laravel.yml
- phpstan.neon
- src/Carbon/Traits/Date.php
- tests/Carbon/MacroTest.php
Fix kylekatarnls/business-day#120
> Re-allow macro with names starting with diff

- src/Carbon/Lang/bs.php
- src/Carbon/Lang/sr.php
- tests/Localization/BsBaTest.php
- tests/Localization/BsCyrlTest.php
- tests/Localization/BsLatnTest.php
- tests/Localization/BsTest.php
- tests/Localization/SrCyrlBaTest.php
- tests/Localization/SrCyrlMeTest.php
- tests/Localization/SrCyrlTest.php
- tests/Localization/SrCyrlXkTest.php
- tests/Localization/SrLatnBaTest.php
- tests/Localization/SrLatnMeTest.php
- tests/Localization/SrLatnTest.php
- tests/Localization/SrLatnXkTest.php
- tests/Localization/SrMeTest.php
- tests/Localization/SrRsLatinTest.php
- tests/Localization/SrRsTest.php
- tests/Localization/SrTest.php
> Update Bosnian translations

- src/Carbon/CarbonInterface.php
- src/Carbon/Traits/Comparison.php
- tests/Carbon/IsTest.php
> Handle null in canBeCreatedFromFormat

- src/Carbon/CarbonInterval.php
- tests/Carbon/DiffTest.php
- tests/CarbonImmutable/DiffTest.php
> Support %a format

- phpstan.neon
- src/Carbon/AbstractTranslator.php
- src/Carbon/CarbonInterface.php
- src/Carbon/CarbonInterval.php
- src/Carbon/Traits/Difference.php
- tests/CarbonInterval/ConstructTest.php
- tests/Language/TranslatorTest.php
> Fix translator and interval serialization

- src/Carbon/Traits/Comparison.php
- tests/Carbon/IsTest.php
> Fix issue with is month check

- src/Carbon/CarbonInterval.php
- tests/Language/TranslatorTest.php
> Unserialize carbon interval created by v2

- .gitignore
- tests/Carbon/ComparisonTest.php
Hellooo 👋🏻 
In this PR I have added more tests for:
> Add more `between()` / `isBetween()` tests

- src/Carbon/Lang/de.php
Added missing period DE translations.
> Added period German translations

- phpstan.neon
- src/Carbon/CarbonInterval.php
- src/Carbon/Traits/Difference.php
- tests/Carbon/DiffTest.php
- tests/Carbon/GettersTest.php
- tests/Carbon/ModifyTest.php
- tests/CarbonImmutable/DiffTest.php
- tests/CarbonInterval/ConstructTest.php
- tests/CarbonInterval/SettersTest.php
- tests/CarbonPeriod/CreateTest.php
> Use pro rata to calculate decimal part of month/year diffs

- src/Carbon/CarbonInterval.php
- tests/CarbonInterval/ConstructTest.php
> Parse microseconds as integer when making from specs

- src/Carbon/Traits/Date.php
- tests/Carbon/SettersTest.php
- tests/CarbonImmutable/SettersTest.php
> Fix immutable return for setUnitNoOverflow

- src/Carbon/Lang/fr_BE.php
- src/Carbon/Lang/fr_LU.php
> Fix month abbreviations for fr_BE/fr_LU

- src/Carbon/Lang/cs.php
- src/Carbon/Lang/sk.php
Fixes #3063 
Adds this functionality to slovak
> Fix month names

- .gitattributes
- psalm.xml
> Add Psalm config

- src/Carbon/Traits/Comparison.php
- tests/Carbon/IsTest.php
> Fix overflow issue for is-month

- .github/workflows/documentation.yml
- .github/workflows/laravel.yml
- .github/workflows/tests.yml
- src/Carbon/CarbonInterval.php
- tests/CarbonInterval/ConstructTest.php
- tests/CarbonInterval/CreateFromFormatTest.php
- tests/CarbonPeriod/GettersTest.php
> Reduce segfault risk in PHP 8.3.20
