src/Carbon/Carbon.php
tests/AddTest.php
tests/DiffTest.php

This PR answers both issues #236 and #217 - in order for the tests to all pass on Travis, it depends on another PR I submitted this morning fixing a `diffForHumans` issue that popped up after the new year.
Although this is influenced by the default PHP behavior, I also think it is worth considering adding an argument flag to the "base" add and subtract methods - the behavior seems counter-intuitive as it is, and it doesn't feel nearly as semantically satisfying to preserve it.
Just a thought - perhaps something like the following, where the overflow method would be protected:
```
public function addMonths($value, $useDefault = false)
{
return $useDefault ? $this->modify((int) $value . ' month') : $this->addMonthsNoOverflow($value);
}
Carbon::now()->addMonths(2); // intuitive behavior …
```

Add / Subtract months with no overflow

---

tests/DiffTest.php

Tests started failing in the `DiffTest` class - this is a quick fix to have those tests pass, using `setTestNow`, to allow for other PRs to be submitted. Actual issue is submitted in [issue 237](https://github.com/briannesbitt/Carbon/issues/237).

Applying fix in tests to get them passing - see Issue #237

---

readme.md
readme.src.md
src/Carbon/Carbon.php
tests/DiffTest.php

When set to true, it modifies the string to only contain the human-readable time difference by omitting modifiers **ago**, **from now**, **before**, and **after**
This is similar to #100, but with passing tests.

Added optional 2nd parameter to diffForHumans

---

readme.src.md

Added a bit more information to the install procedure, since it was using an uppercase `Carbon` which breaks some of composer's new tooling and added a note for users to avoid using `*`
I did not run `readme.php` as it broke many things like the "maxValue" examples.

Updating README

---

src/Carbon/Carbon.php
tests/StringsTest.php

formatLocalized didn't respect the timezone set on a date object. this can be fixed by using ...
strtotime($this)
instead of 
$this->timestamp

timezone support for method formatLocalized

---

src/Carbon/Carbon.php
tests/RelativeTest.php

Wrote these two helpers methods because they are often quite useful. They're based of similar methods in Ruby On Rails found [here](http://api.rubyonrails.org/classes/DateTime.html#method-i-seconds_since_midnight) and [here](http://api.rubyonrails.org/classes/DateTime.html#method-i-seconds_until_end_of_day).
- secondsSinceMidnight gets the number of seconds since midnight of the current Carbon object.
- secondsUntilEndOfDay get the number of seconds from the current Carbon object to 23:59:59 of the current day.

Added secondsSinceMidnight and secondsUntilEndOfDay helper methods

---

src/Carbon/Carbon.php

Because calling format once is better than twice

Optimize birthday

---

src/Carbon/Carbon.php
tests/SettersTest.php

As these functions do not override parent functions

Remove setdate and settime

---

src/Carbon/Carbon.php
tests/GettersTest.php

This time of year usually gives problems with dates. I have a project that works with week numbers.
$date = new \Carbon\Carbon('2014-12-30');
echo $date->weekOfYear .' '.$date->year;
Gives `1 2014`. So the correct usage (in this particular case) is `$date->format('o')`, which gives 2015.
Would it be good to give this a property on the date object? Something like `$date->yearIso` / `$date->IsoYear`? Even though it's not much shorter then `format->('o')` but it might make it more obvious to people with autocomplete etc.

Add yearIso property

---

src/Carbon/Carbon.php

If you use ternary expression, it can be two in one.

Ternary expression

---

src/Carbon/Carbon.php

`$isFuture` can happen a bit later, and calling `gt` is not required

Calculate isFuture a bit later with $$diffInterval

---

src/Carbon/Carbon.php

IDE (eg. PHPStorm) annotation validator reports: Field with the same name is already defined in this class.
Its due annotation has 2 definitions (read-only and write-only) pointing to the same property, which is not correct.

Clean up annotations

---

src/Carbon/Lang/nl.php

The plural of "uur" (hour) is "uren" (hours), but only used when describing clock faces. When describing (relative) time, there's no plural use.

Fixed Dutch translation for hours.

---

tests/CarbonIntervalForHumansTest.php

Added Catalan and Bulgarian unit tests to test months and years. This should add more coverage to language files. Thank you.

Added Catalan and Bulgarian Unit Tests

---

composer.json

This would avoid Laravel 5.1 (development) to resolved to Carbon 1.17
since it require symfony/translation 2.7
Signed-off-by: crynobone <crynobone@gmail.com>

Allow latest Carbon to be installed with symfony/translation 2.7 or later when it become available.

---

.travis.yml

Fix: Composer installs dev dependencies by default

---

src/Carbon/Lang/fa.php

Used in Iran, Tajikistan, Afghanistan. Total Persian speaking population globally is around 120 Million.

Farsi (Persian) Translation

---

readme.md

Enhancement: Use SVG for Travis build status

---

src/Carbon/Lang/he.php

Adding Hebrew to Carbon, allowing ->diffForHumans() to work in hebrew as well.
Made difference between "one minute", "two minutes" and ":n minutes" in HE, as it should.

Adding HE language

---

src/Carbon/Carbon.php

In Israel, week starts at Sunday and ends at Saturday, weekend days are Friday and Saturday
and many other countries has their own weekends and weird calendars.. so I think it might help others
Added:
protected static $weekStartsAt integer (use Carbon::DAYCONST)
protected static $weekEndsAt integer (use Carbon::DAYCONST)
protected static $weekendDays array (array of Carbon::DAYCONST)
public static function getWeekStartsAt()
public static function setWeekStartsAt($day)
public static function getWeekEndsAt()
public static function setWeekEndsAt($day)
public static function getWeekendDays()
public static function setWeekendDays($days)
Updated:
isWeekday() - to use !$this->isWeekend()
isWeekend() - to check if current day is in static::$weekendDays
startOfWeek() - to use static::$weekStartsAt …

Dynamic first/last day of week and weekend days

---

composer.json

If this is working on symfony 2.7 with the BC warnings, then it must be working on Symfony 3.0.

Allow installs with symfony 3

---

src/Carbon/Carbon.php

Fix: Occurence vs. Occurrence

---

src/Carbon/Lang/th.php

Fix: Remove duplicate array key

---

src/Carbon/Carbon.php

On 64 bit systems `maxValue()` and `minValue` produce akward dates (see end for examples) that can not be used for database or html date input fields (see bottom for examples).
I propose to use more common max and min values in the case, that integer values are 64 bit, ie '1001-01-01 00:00:00' to '9999-12-31 23:59:59'.
It is possible to use these values for an html date input field as well as in MySQL for DATE, DATETIME ([MySQL 5.0 Reference Manual: 11.3.1 The DATE, DATETIME, and TIMESTAMP Types](https://dev.mysql.com/doc/refman/5.0/en/datetime.html)). MySQL TIMESTAMP only supports a range of '1970-01-01 00:00:01' UTC to '2038-01-19 03:14:07' UTC.
Examples
=======
64 bit
------
64 bit `maxValue()`  
//PHP_INT_MAX = 9223372036854775807
Carbon {
+"date": "-292277022657-01-27 …

Update Carbon.php: Update minValue() and maxValue() for 64bit systems

---

src/Carbon/Lang/es.php
tests/LocalizationTest.php

Two words were wrong, they were  **before** and **after**, i fixed it!
Great project! :+1:

Fix spanish translation

---

tests/AddTest.php
tests/SubTest.php

Test for attempts to add or subtract weekdays on a weekend. For when someone tries to make an attempt to change add and sub weekends functionality (planning on doing this).

Add test for add and sub weekdays during weekend

---

src/Carbon/Lang/pt_BR.php

Foi trocado duas palavras para melhor entendimento na Língua Portuguesa

Correção palavras pt_BR

---

src/Carbon/CarbonInterval.php

Fixes issue https://github.com/briannesbitt/Carbon/issues/369. This also allows us to construct a new interval using method chaining, where the first method contains a zero timestamp. Example:
CarbonInterval::days(0)->weeks(1);
Jarno

Allow for creation of a zero interval.

---

docs/index.html
docs/index.src.html
index.html
jumbotron.src.html

This PR
Related to https://github.com/briannesbitt/Carbon/pull/438.
/cc @PSmolic
:information_desk_person: This updates the `gh-pages` branch.

Fix: createFromTimestamp() vs createFromTimeStamp()

---

src/Carbon/Carbon.php

Shorter instantiations - and also mimics a bit PHP7 `::` operator

Shorter instantiations

---

composer.json

PHPUnit 5 is the first release to actually say that it supports php 7, so we want to run our tests on php 7, we need to use PHPUnit 5.

Allow phpunit 5 too

---

tests/CarbonInterval/AddTest.php
tests/CarbonInterval/ConstructTest.php
tests/CarbonInterval/ForHumansTest.php
tests/CarbonInterval/GettersTest.php
tests/CarbonInterval/SettersTest.php

The CarbonInterval suffix is not useful anymore as the test class is in its own folder

Remove CarbonInterval suffix

---

src/Carbon/Carbon.php
tests/StartEndOfTest.php

The 1st century AD/CE started on January 1, 1 and ended on December 31, 100. 
https://en.wikipedia.org/wiki/Century

Fix start/end of century.

---

src/Carbon/Carbon.php

Calling `hour` then `minute` then `second` call 3 times `setTime` via `__set`.
We can thus call it only once.

Avoid using setTime many times

---

tests/Carbon/LocalizationTest.php
tests/Localization/Da.php
tests/Localization/De.php
tests/Localization/Es.php
tests/Localization/Fa.php
tests/Localization/Fo.php
tests/Localization/Fr.php
tests/Localization/It.php
tests/Localization/Ja.php
tests/Localization/Ko.php
tests/Localization/Lt.php
tests/Localization/Tr.php

Reorganize localizations tests.
`\Tests\Carbon\LocalizationTest` takes care of checking file presence, setting locale and setting translator
Each language has its own test file in `Tests\Localization` namespace.

Reorganize localizations tests

---

src/Carbon/Carbon.php
tests/GettersTest.php

Ability to pass offset instead of timezone name was very needed for one of my project, and I decided to create a pull request.

Added ability to pass offset in hours instead of timezone name

---

tests/Carbon/AddTest.php
tests/Carbon/DiffTest.php
tests/Carbon/StringsTest.php
tests/Carbon/SubTest.php
tests/Carbon/TestingAidsTest.php

* Use `\Tests\Carbon\DiffTest::wrapWithTestNow` and rename `$notNow`variable to `$testNow`
* Use lighter ternary	 in `\Tests\Carbon\DiffTest::wrapWithTestNow`
* Blank line between each functions in `\Tests\Carbon\StringsTest`
* Reformat some comments

Work on tests

---

src/Carbon/Carbon.php
tests/Carbon/InstanceTest.php

If `$dt` is a an instance of `\Carbon\Carbon`, no need to go again into `\Carbon\Carbon::__construct`

Tweak \Carbon\Carbon::instance

---

src/Carbon/Carbon.php
tests/Carbon/SettersTest.php

https://github.com/briannesbitt/Carbon/issues/539
Calling modify before setDate releases whatever is locking the day.

Workaround for PHP bug

---

tests/AbstractTestCase.php

Useless to run multiple assertions where we can make a single assertion on an array of actual and expected properties

Use only one assertion

---

src/Carbon/Carbon.php

Based on this thread: https://github.com/briannesbitt/Carbon/issues/435
I don't see a reason to go through the full instantiation for a copy, clone should work fine.

Optimize Copy

---

src/Carbon/Carbon.php
tests/Carbon/ModifyTest.php

Fix issue 88

---

.php_cs
.styleci.yml

Arrows are not aligned in the code - there is no reason they should be aligned in lang files.
Plus it's adding useless noise when adding or removing an element in the array

Unalign array arrows

---

src/Carbon/Carbon.php
tests/Carbon/GettersTest.php

I've had trouble with my date math in a project because 2015 has 53 weeks in it, not 52. I would like to add a method to check and see if this year is a "long year", [according to the ISO standard](https://en.wikipedia.org/wiki/ISO_week_date#Weeks_per_year).
According to [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601#Week_dates), "28 December is always in the last week of its year." So I just made a new Carbon instance on the 28 of December for the year, and check if the week number is 53.
I fully tested the method according to your standards. It's an easy method to add, and one that would be very helpful in our project. Please merge :)
(P.S. I got this idea from [Glavić's post on StackOverflow](http://stackoverflow.com/a/21480444/2916818)).

Add getter to test for "long years"

---

src/Carbon/Carbon.php
src/Carbon/Exceptions/InvalidDateException.php
tests/Carbon/CreateSafeTest.php

This is a PR concerning #583
Note:
* `createSafe`, I could not find a better name.
* `checkDate` is not reliable at the moment as we can only enter a year in of 0-9999 range, `checkDate` allows 0-32767
* We wish to indicate which argument throws an exception and with which value
* Should the `createSafe` only allows hour, minute and second arguments to be ignored (set to null) ? 
Suggestions are welcomed.
----

Add createSafe

---

src/Carbon/Lang/tr.php
tests/Localization/TrTest.php

Meaning of "from now" on dictionary is not suitable for the usage of package like the example; "3 yıl andan itibaren" (translation of 3 years from now) doesn't make sense. It should be "sonra" as both Google translate and jenssegers/date use it.

Tr translate fix

---

src/Carbon/Carbon.php
tests/Carbon/AddTest.php

* Make sure the same instance of `\Carbon\Carbon` is returned.
* Also update tests to make sure the hours, minutes and seconds are not modified.
---
Fix #621

Fix issue #621

---

tests/Carbon/GettersTest.php

These 2 functions test exactly the same thing. One of them can be removed.

Remove duplicate test function

---

src/Carbon/Carbon.php

No need to call `\Carbon\Carbon::__get`

Directly call \DateTime::getTimezone

---

.gitattributes

Remove CONTRIBUTING.md from export-ignore: this file does not exist

Remove CONTRIBUTING.md from export-ignore

---

src/Carbon/Carbon.php
tests/Carbon/TestingAidsTest.php

```
Carbon::setTestNow(Carbon::parse('2000-01-01 00:00:00'));
// 1999-12-31 00:00:00, Good!
$carbon = Carbon::parse('yesterday');
var_dump($carbon->toDateTimeString());
// 2016-03-16 00:00:00, Bad!
$carbon = Carbon::parse('today');
var_dump($carbon->toDateTimeString());
// 2000-01-01 00:00:00, Good!
$carbon = Carbon::parse('now');
var_dump($carbon->toDateTimeString());
// 2000-01-02 00:00:00, Good!
$carbon = Carbon::parse('tomorrow');
var_dump($carbon->toDateTimeString());
```

Add 'today' to RelativeKeywords

---

tests/AbstractTestCase.php
tests/Localization/DaTest.php
tests/Localization/DeTest.php
tests/Localization/EsTest.php
tests/Localization/FaTest.php
tests/Localization/FoTest.php
tests/Localization/FrTest.php
tests/Localization/GlTest.php
tests/Localization/HyTest.php
tests/Localization/ItTest.php
tests/Localization/JaTest.php
tests/Localization/KaTest.php
tests/Localization/KoTest.php
tests/Localization/MkTest.php
tests/Localization/NlTest.php
tests/Localization/PtTest.php
tests/Localization/TrTest.php
tests/Localization/UrTest.php
tests/Localization/ZhTest.php

In some occassions, interval tests fail when they are run on a month when a DST change happens: a non-DST date should always be used for these tests.

[WIP] Fix interval tests

---

src/Carbon/Carbon.php
tests/AbstractTestCase.php
tests/Carbon/AddMonthsTest.php
tests/Carbon/AddTest.php

Add an overflow behavior.
``` php
Carbon:: useMonthsOverflow(false);
```
By default `addMonths` will work with overflow as `\DateTime` does, so that there is no breaking change.
---
Related to #37, #236, #428, #529 and #627

Add overflow behaviour

---

src/Carbon/Carbon.php

age : no need to cast twice to int

---

src/Carbon/Carbon.php

And no need to call `__get` twice.

Simplify __set

---

src/Carbon/Carbon.php

Prefer docblock with `@return static`

Prefer docblock with return static

---

.travis.yml

- No need to cover all builds, only PHP7 is fine
- No need to suggest package
- Disable xdebug when it's not required.

Speed up travis and codecov

---

src/Carbon/Carbon.php

As discussed in #819 there are language variants that allow script type to be passed in the format `ll-Ssss-RR` (`l` being language code, `s` being script used, `r` being the region).
According to http://symbolcodes.tlt.psu.edu/bylanguage/serbocroatian.html website, there are three variants for Montenegrin locale:
- `sr-ME` (Montenegrin, script unspecified)
- `sr-Cyrl-ME` (Montenegrin in Cyrillic)
- `sr-Latn-ME` (Montenegrin in Latin Script)
This reflects the situation in real life, as both scripts (Latin and Cyrillic) are equally used in Montenegrin, Serbian, Croatian and Bosnian languages - as far as I know.
This is a non-breaking change.

Allow Carbon::setLocale to accept long localization variants

---

src/Carbon/Carbon.php
tests/Carbon/IsTest.php

Added the new methods `isNextWeek, isLastWeek, isNextMonth, isLastMonth, isNextYear, isLastYear`
Use case was to has a quick method when sorting data into last, current and next week segments, so seemed sensible to have it for month and year also.
---
Closes https://github.com/briannesbitt/Carbon/pull/752

Add new isNext- / isLast- methods

---

src/Carbon/Carbon.php
tests/Carbon/TestingAidsTest.php

Change Carbon::setTestNow() to be able to parse a string.

---

.gitattributes
.travis.yml
phpstan.neon
src/Carbon/Carbon.php
src/Carbon/CarbonInterval.php
tests/AbstractTestCase.php
tests/Carbon/StringsTest.php
tests/Localization/EnTest.php
tests/Localization/KmTest.php
tests/Localization/SrMeTest.php
tests/Localization/UzTest.php

This is a PR for integrating static analysis tool [PHPStan](https://github.com/phpstan/phpstan) that focuses on finding bugs and running in your CI build. It found a few issues that I put in separate commits.

Integrating PHPStan & fixes of found issues

---

tests/Carbon/CreateTest.php

Fix failing tests
---
The following tests are sometimes failing - this PR fixes that, without modifying them:
- `\Tests\Carbon\CreateTest::testCreateWithDefaults` 
- `\Tests\Carbon\ComparisonTest::testEqualToTrue`

Fix failing tests.

---

tests/AbstractTestCase.php
tests/Carbon/ConstructTest.php
tests/Carbon/CreateTest.php
tests/Carbon/SettersTest.php
tests/Carbon/TestingAidsTest.php

Always Carbon::setTestNow
---
This allows to avoid errors on timestamp comparisons when TravisCI tests are a bit slow

Always Carbon::setTestNow

---

tests/Carbon/IsTest.php

Fix tests for `isLastMonth` and `isNextMonth`.
---
Related to #846 and #752

Fix tests for isLastMonth and isNextMonth.

---

docs/index.src.html

I removed a statement in the docs about approximation in `diffForHumans()` that does not hold anymore.

[docs] No approximation is used anymore.

---

composer.json

Symfony 4 is about to land :tada: :champagne:, and the breaking changes to the Translate component aren't relevant to Carbon … and your wonderful little library is used pretty heavily out there. :heart: 
So here we go :smile: 
Closes: #1049

Add Syfmony 4.0 constraint

---

readme.md

missing empty lead to "without composer" not being rendered as header

fix readme markdown format

---

.gitattributes
composer.json

There was an error on the win:
```
> composer test
> ./vendor/bin/phpunit; ./vendor/bin/php-cs-fixer fix -v --diff --dry-run;
The system cannot find the path specified.
Script ./vendor/bin/phpunit; ./vendor/bin/php-cs-fixer fix -v --diff --dry-run; handling the test event returned with error code 1
```
In the composer documentstion [written](https://getcomposer.org/doc/articles/scripts.md#writing-custom-commands) that
> Note: Before executing scripts, Composer's bin-dir is temporarily pushed on top of the PATH environment variable so that binaries of dependencies are easily accessible. In this example no matter if the phpunit binary is actually in vendor/bin/phpunit or bin/phpunit it will be found and executed.

Composer scripts refactored mainly to work on the Windows

---

.gitattributes

> I have a Windows 7. When i run php-cs-fixer all files marked "changed" because theirs EOL was changed from CRLF to LF.
> But why they have CRLF initially?
> It is because `* text=auto` in `.gitattributes`. It means that all files that considered as text will have system-related EOL in working directory. On windows it is CRLF.
> But php-cs-fixer dont bother what is the current system - it always make EOL = LF.

Fix issue #885

---

docs/index.html
docs/index.src.html
generate.php

Documentation for:
- static useMonthsOverflow
- static resetMonthsOverflow
- static shouldOverflowMonths
- addMonthsWithOverflow
- addMonthWithOverflow
- addMonthsNoOverflow
- addMonthNoOverflow
- subMonthsWithOverflow
- subMonthWithOverflow
- subMonthsNoOverflow
- subMonthNoOverflow

Document overflow methods

---

src/Carbon/Carbon.php

Extremely minor cosmetic change to the `isSameAs` method doc block to make it a "correct" method doc block.

Add asterisk to isSameAs doc block

---

src/Carbon/Carbon.php
tests/Carbon/ConstructTest.php

Since PHP 7.1 DateTime supports microseconds:
> 7.1 | From now on microseconds are filled with actual value. Not with '00000'.
http://php.net/manual/en/datetime.construct.php#refsect1-datetime.construct-changelog
The constructor when using a mocked time was converting date with the format string:  `Y-m-d H:i:s`. 
This meant that it was losing the microseconds part. 
When using a mocked time with comparison operators you could end up in some weird errors because the microseconds part was 0 on all mocked times.
```php
$c = new Carbon('2017-12-20 15:38:22.1234');
Carbon::setTestNow($c);
$mockedC = Carbon::now();
printf("%s\n", $c->format("Y-m-d H:i:s.u"));       // 2017-12-20 15:38:22.123400
printf("%s\n", $mockedC->format("Y-m-d H:i:s.u")); // 2017-12-20 15:38:22.000000
var_export($c == …
```

Fix issue with mocking time on PHP >=7.1

---

.travis.yml

Allow to run tests on the gh-pages branch, this will be used to count documented methods and fail the gh-pages branch build if a new method miss its documentation.

Run TravisCI tests for gh-pages branch

---

check.php
docs/index.html
docs/index.src.html

- Document getLocale
- Cleanup spaces
- Remove native DateTime methods from the check command

Document getLocale

---

src/Carbon/Carbon.php
tests/Carbon/CreateFromTimeTest.php

These 2 functions should have no business doing Carbon library which uses supreme DateTime class.
They are also causing bugz when user enters other timezone than the one he has set globally. See issue https://github.com/briannesbitt/Carbon/issues/983.

Removed date() and time() functions from Carbon::create()

---

src/Carbon/Carbon.php
tests/AbstractTestCase.php
tests/Carbon/CreateFromTimestampTest.php

Here is simple fix for #232.  We're still extremely limited in terms of what PHP allows us to do, unfortunately.  All this does is ensure that the milliseconds will appear in the DateTime object.  I'm not thrilled with the method name, but couldn't think of anything more clever.  Feel free to suggest an alternative.

Added createFromTimestampMs method to parse timestamps in milliseconds.

---

src/Carbon/Carbon.php

I think the optimization is worth it, as this method may be called thousands of times.
* Use the language construct `isset()` instead of the function `array_key_exists()`
* Use a static variable

Optimize the magic properties getter

---

src/Carbon/Carbon.php
tests/Carbon/LastErrorTest.php

getLastErrors returnes null when create Carbon with __constructor

Fixed issue #891 - getLastErrors

---

src/Carbon/Carbon.php
tests/Carbon/DiffTest.php

diffForHumans() $parts parameter is ignored when injecting the remaining days after subtracting weeks.  Added test to confirm.

Fixed bug $parts parameter is ignored

---

src/Carbon/Carbon.php
tests/Carbon/InstanceTest.php

Laravel uses __set_state() to set the value of config items when retrieving them from its config cache. Without the method being implemented in Carbon, the DateTime::__set_state() is used and so any Carbon instances defined in the config are converted to DateTime if the cache is used.

Add __set_state() method, fixes issue with Laravel's config cache

---

check.php
docs/index.html
docs/index.src.html

- Update Timezone examples
- Document centuries and quarters methods
- Fix overflow examples
- Document diff parameters
- Add examples for first*, last*, nth* methods

Fix documentation

---

src/Carbon/Carbon.php
tests/Carbon/IsTest.php

Methods `isSame**()` should also accept \DateTime objects.

---

src/Carbon/Carbon.php
tests/Carbon/CreateFromTimestampTest.php

Work-around for bug https://bugs.php.net/bug.php?id=67127

Fix #1073 Handle microseconds for locales with coma decimal separator

---

src/Carbon/Carbon.php
tests/Carbon/AddTest.php

This adds the ability to set carbon to not overflow months when adding a year. For example, see the following:
```
Carbon\Carbon::parse('2016-02-29')->addYear()->toDateString(); // 2017-03-01
```
However, you can set the option to tell carbon to not overflow months like:
```
Carbon\Carbon::useMonthsOverflow(false);
```
This means:
```
Carbon\Carbon::parse('2016-01-31')->addMonth()->toDateString(); // 2016-02-28
```
This PR adds similar functionality so that:
```
Carbon\Carbon::parse('2016-02-29')->addYear()->toDateString(); // 2017-02-28
```

Adding support for not overflowing months when adding a year

---

src/Carbon/Carbon.php
tests/Carbon/StringsTest.php

Many times, I prefer to store my times in ISO8601 Zulu format
>Y-m-d\TH:i:s\Z
Right now, when doing `->toIso8601String()` it returns it in the current timezone.  
This PR adds a `->toIso8601ZuluString()` that will convert the current time instance to UTC and format it in the proper ISO8601 Zulu Formatted String.
A test has been written to check functionality.
reference for Zulu: https://tools.ietf.org/html/rfc3339#section-2

Zulu ISO8601 String Helper

---

src/Carbon/Carbon.php
tests/Carbon/RelativeDateStringTest.php

Fixes #940 by extending the relative keyword list to include bare weekdays; added test coverage for this edge case.

Fixes #940 by extending the relative keyword list

---

src/Carbon/Carbon.php
tests/Carbon/DiffTest.php

After #1091, createFromDate with different timezones will no longer have a gap.
Meaning that this code:
```php
Carbon::createFromDate(2012, 1, 1, 'America/Toronto')->diffInHours(
Carbon::createFromDate(2012, 1, 1, 'America/Vancouver')
)
```
Returned 3 before #1091 and will return 0 or 24 after #1091 depending on the current time.
That is more correct in my opinion but as the consequences of the mix `Input Date` + `Current time` + `Input Timezone` can be unexpected, that's why I propose to add, document and promote a `createMidnightDate` method that would be `Input Date` + `00:00:00` + `Input Timezone`, this way there is no dynamic unknow part in the produced Carbon instance, and the following code would return `3`:
```php
Carbon::createMidnightDate(2012, 1, 1, …
```

Test diff in hours with timezones

---

src/Carbon/Carbon.php
tests/Carbon/IsTest.php

This PR adds a method to check if a string is in a given datetime format. Would be glad to see this merged.
Note: the regex patterns could perhaps be shortened but I preferred a readable pattern...

Implement hasFormat() method

---

src/Carbon/CarbonInterval.php
tests/CarbonInterval/CompareTest.php

Adds simple compare method to compare current interval with another (because php does now have build-in functions for it, like for DateTime)

Add compare method to CarbonInterval

---

src/Carbon/Carbon.php
tests/Carbon/CreateSafeTest.php
tests/Carbon/PhpBug72338Test.php
tests/Carbon/SerializationTest.php

- Handle bad DST dates
- Avoid to modify twice the date
- Do a complete check of input values against created values

Do a complete check (date, DST, etc.) in createSafe

---

.gitignore
build.php
composer.json

This script allows to generate a stand-alone package for a given release. This will includes symfony/translation and all Carbon possible future and/or nested dependencies.
It also add the version in a documentation comment block.
Builds generated this way could be added to GitHub releases.

Add a build system to package Carbon and its dependencies

---

src/Carbon/Carbon.php
tests/Carbon/LastErrorTest.php
tests/Carbon/TestingAidsTest.php

- Use the testNow instance everywhere a relative time is generated
- Add some tests for hasRelativeKeywords and isRelativeTimeString
- Optimize hasRelativeKeywords

Use a real relativity test instead of a RegExp detection

---

src/Carbon/Carbon.php

The bug is if `version_compare(PHP_VERSION, '7.1.3-dev', '>=') && version_compare(PHP_VERSION, '7.1.4-dev', '<')` is true then the whole if statement is true.

Fix constructor bug

---

.php_cs.dist
tests/Carbon/CreateFromTimeTest.php
tests/Carbon/CreateSafeTest.php
tests/Carbon/DayOfWeekModifiersTest.php
tests/Carbon/DiffTest.php
tests/Carbon/ModifyNearDSTChangeTest.php
tests/Carbon/PhpBug72338Test.php

* Make .php_cs.dist compatible with PHP 5.3
* Correct spelling for some unit-test methods and comments

Unit tests fixes

---

.php_cs.dist
tests/Carbon/CreateFromTimeTest.php
tests/Carbon/CreateSafeTest.php
tests/Carbon/DayOfWeekModifiersTest.php
tests/Carbon/DiffTest.php
tests/Carbon/ModifyNearDSTChangeTest.php
tests/Carbon/PhpBug72338Test.php

* Fix unit-tests (`testAddHourPassingArg`, `testMicroGetterWithDefaultNow`) while running on Windows
* Correct spelling for some unit-test methods and comments

* Make .php_cs.dist compatible with PHP 5.3

---

build.php
src/Carbon/Carbon.php
tests/Carbon/CreateFromTimeStringTest.php
tests/Carbon/SettersTest.php

- Build script: add "missing" option and better tags detection
- Implement `createFromTimeString()` #919
- Enable microseconds setting in `setTimeFromTimeString()` for PHP >= 7.1
- Remove "now" fallback microseconds from `createFromTimestamp()` on PHP 7.0

Create createFromTimeString() method

---

src/Carbon/Carbon.php
tests/Carbon/GettersTest.php

- Add useMicrosecondsFallback()
- Add isMicrosecondsFallbackEnabled()
- Calculate microtime and timestamp in the exact same moment

Microseconds improvements

---

tests/Carbon/AddTest.php
tests/Carbon/NowAndOtherStaticHelpersTest.php

- Pick an hour that can't take in DST in Toronto
- Avoid failure if time changed before the two statements

Fix unit tests

---

src/Carbon/Carbon.php
tests/Carbon/ModifyTest.php

Add methods using timestamp instead of intervals:
- addRealSecond
- addRealSeconds
- subRealSecond
- subRealSeconds
- addRealMinutes
- addRealMinute
- subRealMinutes
- subRealMinute
- addRealHours
- addRealHour
- subRealHours
- subRealHour
- diffInRealSeconds
- diffInRealMinutes
- diffInRealHours
And re-order add/sub methods the following sorting: biggest-to-smallest unit, add then sub, plural then singular.

Re-introduce real seconds/minutes/hours as dedicated methods

---

src/Carbon/CarbonInterval.php
tests/CarbonInterval/FromStringTest.php

Creates a CarbonInterval from string in JIRA format (solves #997)
Format:
Suffix | Unit    | Example | DateInterval expression
------ | ------- | ------- | -----------------------
y    | years   |   1y    | P1Y
M    | months  |   3M    | P3M
w    | weeks   |   2w    | P2W
d    | days    |  28d    | P28D
h    | hours   |   4h    | PT4H
m    | minutes |  12m    | PT12M
s    | seconds |  59s    | PT59S
e. g. `1w 3d 4h 32m 23s` is converted to 10 days 4 hours 32 minutes and 23 seconds.
Special cases:
- An empty string will return a zero interval
- Fractions are allowed for weeks, days, hours and minutes and will be converted
and rounded to the next smaller value (caution: 0.5w = 4d)

create CarbonInterval::fromString(string) method

---

src/Carbon/Carbon.php
tests/Carbon/SetDateAndTimeFromTest.php

This adds the two new methods `matchDate` and `matchTime`, which sets the `year`, `month`, and `day` or `hour`, `minute`, and `second` respectively, based on the passed datetime.
This is based on discussions in #918. I decided to add these more explicitly named methods instead of overloading the existing `setDate` and `setTime` methods, but I'm happy to make any changes to naming etc., if deemed more appropriate.

Add methods to set date or time from another instance

---

composer.json
phpstan.neon
src/Carbon/Carbon.php
src/Carbon/CarbonInterval.php
src/JsonSerializable.php
tests/Carbon/Fixtures/Mixin.php
tests/Carbon/InstanceTest.php
tests/Carbon/JsonSerializationTest.php
tests/Carbon/MacroTest.php

- Implement macro/hasMacro/mixin
- Implement JSON methods
- Allow json_encode/json_decode Carbon instances with PHP >=5.4
- Allow `$this` usage in macros with PHP >=5.4

Implement macro and JSON serialization in a PHP 5.3 compatible way

---

src/Carbon/CarbonInterval.php

1. You cannot set days on DateInterval object. > https://3v4l.org/M9lqa
2. Even if it could be set, DateInterval created with DateTime::diff() is not allowed (few lines before).

Removed dead code.

---

src/Carbon/Lang/it.php
tests/Localization/ItTest.php

The correct way to say it in Italian is "tra 2 ore", otherwise it could be misunderstood as if the date is in the past.

Fix Italian translation for from_now

---

src/Carbon/Carbon.php
tests/Carbon/IsTest.php

This adds 6 methods for more fine-granular comparison of hours, minutes and seconds.
- isSameHour / isCurrentHour
- isSameMinute / isCurrentMinute
- isSameSecond / isCurrentSecond
Tests are in place and ran successfully, i also unified the PHPDocs for related methods and added a comment mentioning planned changes to align the behaviour of `isSameMonth()` with the other methods.

Add methods for granular comparison (mentioned in #1248)

---

src/Carbon/Carbon.php
tests/Carbon/InstanceTest.php

This allow to create a Carbon instance from multiple possible formats. For example, if you have both date with and without microseconds, you can first try to get microsecond, then if the format does not match fallback to format without microseconds (see `testInstanceFromMultipleFormats`).
This can also allow some user multiple input such as: `array('Y-m-d', 'm/d/Y', 'n/j/Y', 'm/d/y')`
An alias `createFromFormats` allow to call with both singular and plural form.

Allow to create from multiple formats

---

src/Carbon/Carbon.php
src/Carbon/CarbonInterval.php
tests/CarbonInterval/CascadeTest.php
tests/CarbonInterval/TotalTest.php

This PR adds two new `CarbonInterval` methods: `cascade()` and `total($unit)`, accompanied by `total<unit>` getters:
```php
echo CarbonInterval::months(76)->forHumans(); // 29 months
echo CarbonInterval::months(76)->cascade()->forHumans(); // 2 years 5 months
```
```php
$interval = CarbonInterval::fromString('3h 30m');
echo $interval->hours * 3600 + $interval->minutes * 60; // 12600
// even more useful when string can contain any units
echo CarbonInterval::fromString('3h 30m')->totalSeconds; // 12600
```
Methods functionality is slightly different, but both are based on the same `static::$cascades` mapping, thus I added both in the same pull request.
Let me know what you think!
I'm also open for suggestions about names, current may be a bit ambiguous.

Simpler unit conversions in CarbonInterval

---

src/Carbon/Lang/nl.php

```
There is still one string that I could  not translate,  since that does
not exist in Dutch.
If anyone else knows the word for "before yesterday" in English, please
leave a comment on the PR.
"Voorgisteren" would be the closest I can imagine, but its not correct.
Closing briannesbitt/Carbon#1272
Signed-off-by: MegaXLR <admin@megaxlr.net>
```

Add Diff translations for Dutch

---

src/Carbon/Carbon.php
tests/Carbon/TestingAidsTest.php

Let's say current time is:
```php
Carbon::now(); // 2018-05-10 16:22:30 America/Toronto
```
We set the mock instance to:
```php
Carbon::setTestNow('2013-09-01 05:10:15 America/Vancouver');
```
One would expect that when using `Carbon::createFromFormat` with a partial format, the missing part will be filled from the mock:
```php
Carbon::createFromFormat('Y-m-d', '2016-06-10'); // 2016-06-10 05:10:15 America/Vancouver
Carbon::createFromFormat('H:i:s', '10:20:30'); // 2013-09-01 10:20:30 America/Vancouver
```
However as of now it is filled from the actual time instead:
```php
Carbon::createFromFormat('Y-m-d', '2016-06-10'); // 2016-06-10 16:22:30 America/Toronto
Carbon::createFromFormat('H:i:s', '10:20:30'); // 2018-05-10 10:20:30 America/Toronto
```
This PR fixes that issue, by prepending …

Respect mock instance in createFromFormat with partial format

---

src/Carbon/Carbon.php

The previous phpdoc comment is inappropriate.
So, I have replace it with the content from the official documentation ([https://carbon.nesbot.com/docs/](https://carbon.nesbot.com/docs/)).
Signed-off-by: codekaar <kharelbarun@gmail.com>

Update phpdoc comment with content from official documentation

---

src/Carbon/CarbonPeriod.php
tests/CarbonInterval/ToPeriodTest.php
tests/CarbonPeriod/AliasTest.php
tests/CarbonPeriod/CreateTest.php
tests/CarbonPeriod/FilterTest.php
tests/CarbonPeriod/IteratorTest.php
tests/CarbonPeriod/SettersTest.php
tests/CarbonPeriod/ToArrayTest.php
tests/CarbonPeriod/ToStringTest.php

Changes:
1. Removed caching of iteration results.
- Every `toArray`, `count`, `first`, `last` call will cause a full iteration.
- Initialization is done when current is null (only before first iteration).
- Validation result is still cached per iteration.
2. Removed start date filter.
- Start date is used only for initialization during rewind. Changing it during the iteration will have no effect whatsoever.
- DateInterval can now be inverted during iteration.
3. Start date is now required.
- Exception will be thrown when null is passed to setter, similarly to DateInterval.
- By default start date is set to now.

Update carbon period

---

src/Carbon/CarbonPeriod.php
tests/CarbonPeriod/CreateTest.php
tests/CarbonPeriod/SettersTest.php

I looked through the code to check if everything looks good and ended up changing a few things here ad there.
@kylekatarnls Did you think about renaming "recurrences" to "limit"? I think it describes what the filter does better and avoids confusion with how DatePeriod recurrences work. This would give us freedom to implement native recurrences filter later and avoid conflict with DatePeriod if we decide to extend it after it's fixed.

CarbonPeriod final touches

---

src/Carbon/Carbon.php

Carbon::createFromFormat() has been changed to return false for compatibility with php DateTime::createFromFormat() method
http://php.net/manual/en/datetime.createfromformat.php#refsect1-datetime.createfromformat-returnvalues

Change createFromFormat for compatibilty with php DateTime::createFromFormat()

---

docs/index.html
history/index.html
history/index.src.html

- removed CarbonPeriod entry
- summarized "Added getCascadeFactors, setCascadeFactors, ..."
- added workaround for timezone bug, supprt for macros and invert method
- reordered
https://github.com/briannesbitt/Carbon/compare/version-1.27...version-1.28

Fix history for version 1.28

---

tests/CarbonPeriod/SettersTest.php

This test would fail last day of the month up until the 10th into the next month, when single-digit days of the month are being compared.
```php
Carbon::today()->format('d H')
// '01 01'
```
```php
$d2 = Carbon::today()->day
// 1
"$d2 01"
// '1 01', doesn't match above
```
Instead format without the leading zero:
```php
Carbon::today()->format('j H')
// '1 01'
```

Fix testFluentSetters() day comparison

---

tests/Carbon/MacroTest.php

The Easter macro in the test suite would actually fail on a day like today that falls on the 31st. The tests are run as June 27, 2017 so a bug in that macro wouldn't be apparent to anyone that used this implementation in their own codebase.
```php
Carbon\Carbon::setTestNow('2018-05-31 11:30')
Carbon\Carbon::create('2019')->month(4)->day(21);
// { date: 2019-05-21 11:30:00.0 UTC (+00:00) }
$easter = Carbon\Carbon::create('2019');
// { date: 2019-05-31 11:30:00.0 UTC (+00:00) }
$easter->month(4);
// { date: 2019-05-01 11:30:00.0 UTC (+00:00) }
// there is no April 31, 2019
$easter->day(21);
// { date: 2019-05-21 11:30:00.0 UTC (+00:00) }
```
I'd argue such a macro should use midnight as the Easter timestamp but that affected day diff assertions being off by one so I left them as-is.

Correct Easter macro implemention used by test suite

---

docs/index.html
docs/index.src.html

- Add month to week and year to day use cases for CarbonInterval cascade
- Expand on what precision is missing for cascade
- Fix typo Carbon -> CarbonInterval

Add more cascade use cases to examples

---

src/Carbon/Carbon.php
tests/Carbon/SetStartEndOfWeekTest

If set start of a week more than 6 or less than 0 and then call startOfWeek we will get an infinite while loop... So, I think it is a good idea to throw Exception when a user sets start/end of a week.

Wrong day of a week exception

---

src/Carbon/Traits/Date.php
src/Carbon/Traits/Difference.php
tests/Carbon/DiffTest.php
tests/Carbon/GettersTest.php
tests/Carbon/RoundTest.php
tests/CarbonImmutable/RoundTest.php

- Add $weekStartsAt/$weekEndsAt optional arguments for week methods
- Deprecate many static setters
- Fix #1386 weekNumberInMonth for months starting a sunday
- Implement methods from, fromNow, to, toNow

Add $weekStartsAt/$weekEndsAt optional arguments for week methods

---

src/Carbon/Carbon.php
tests/Carbon/StringsTest.php

Currently you can only use a string to set a default __toString() format.
This allows a closure to be used, which will execute whenever the instance is converted to a string.
This allows conditional formatting based on the current value.
For example:
```php
Carbon::setToStringFormat(function ($dateTime) {
return $dateTime->isCurrentYear() ? 'M jS' : 'M jS, Y';
});
echo Carbon::now(); // July 19th
echo Carbon::now()->subYears(2); // July 19th, 2016
```

Support closure based $toStringFormat

---

src/Carbon/Carbon.php
tests/AbstractTestCase.php
tests/Carbon/StartEndOfTest.php

The endOf* methods were inconsistent when it comes to microseconds. The endOfDay method sets the microseconds to 999999, while the endOfHour and endOfMinute doesn't.
Also there was no startOfSecond/endOfSecond method, which is very useful when it comes to microsecond handling.
Added microsecond conditions to the tests of the startOf/endOf methods, and made the assertCarbon handle the microsecond comparison based on PHP version instead of having to do that in the test method itself.

Add start/end of second, make the microsecond handling more consistent

---

src/Carbon/Lang/ca.php
tests/Localization/CaTest.php

'from_now' current translation is wrong. It is a literal spanish translation from "dentro de x días / semanas" that can be understood in Catalan but is grammatically wrong.

Patch catalan translation

---

src/JsonSerializable.php

This makes sure that the interface does not override the PHP provided interface.

Add interface_exists check

---

src/Carbon/Traits/Comparison.php
tests/CarbonImmutable/ComparisonTest.php

The short hand versions doesn't really help with the readability of the code and since both functions (short hand and fully named functions) exist we should be promoting clean readable code. This will aid in the deprecation of the short hand functions at a later date. 
- Move the short hand functions to be aliases of the full named functions

Refactor the comparison functions

---

docs/index.html
docs/index.src.html

In #1434 we changed the logic to be in the longer named functions. This is a change to the docs so we can start to point people to use the longer function names.
Not sure if this is the way to update the docs - so any feedback is appreciated :)
Thanks!

Update the documents to use the longer format functions as a default

---

readme.md

As Carbon no longer is a single file library, the current information is outdated and does not work anymore.

Update without-composer instructions

---

tests/Carbon/LocalizationTest.php
tests/CarbonPeriod/ToArrayTest.php

Looking at some tests I saw that they can be refactored for better understanding, either from the one who reads the tests or when a test fails and show a error message.
Some tests were refactoring using:
`assertArrayHasKey`, `assertArrayNotHasKey` instead of isset function;
`assertCount`

Refactoring tests

---

src/Carbon/Laravel/ServiceProvider.php
tests/Laravel/App.php
tests/Laravel/ServiceProviderTest.php

Only run the locale update if the 'events' and 'translator' services are registered in the container.

Run locale update only if services are registered

---

src/Carbon/Traits/Comparison.php
tests/Carbon/IsTest.php

Fixes the regex validation of the format string, which previously didn't correctly deal with escaped characters.

Fix character escaping in hasFormat()

---

src/Carbon/Traits/Creator.php
src/Carbon/Traits/Date.php
tests/AbstractTestCase.php
tests/Carbon/InstanceTest.php
tests/Carbon/SettersTest.php
tests/Carbon/StringsTest.php
tests/CarbonImmutable/InstanceTest.php
tests/CarbonImmutable/StringsTest.php

- Keep settings through instance method
- Fix microseconds lost on shiftTimezone()
- Add instance() test with timezone
- Allow UTF-8 tests to run on Windows

Instance copy settings

---

src/Carbon/CarbonTimeZone.php
src/Carbon/Traits/Comparison.php
src/Carbon/Traits/Creator.php
src/Carbon/Traits/Date.php
tests/AbstractTestCase.php
tests/Carbon/CreateTest.php
tests/Carbon/GettersTest.php
tests/Carbon/IsTest.php
tests/Carbon/StrictModeTest.php
tests/CarbonImmutable/CreateTest.php
tests/CarbonImmutable/DiffTest.php
tests/CarbonImmutable/GettersTest.php
tests/CarbonImmutable/IsTest.php
tests/CarbonTimeZone/ConversionsTest.php
tests/CarbonTimeZone/CreateTest.php

- Provide methods to get offset/region name from a timezone and convert it from one to the other
- Allow numeric (hour/minute offset) timezone as names
- Fix #1564

Allow numeric (hour/minute offset) timezone as names

---

composer.json

Used interfaces `\Symfony\Component\Translation\TranslatorInterface` and `\Symfony\Component\Translation\TranslatorBagInterface` are compatible from `3.4` to `4.0` so why should we lock out users of still supported Symfony 3.4 ☺

Support for symfony/translation ^3.4

---

src/Carbon/Lang/nl_BE.php

Belgian Dutch differs very little from regular Dutch, mostly only by pronunciation and some French influences in number and date notations.
Let's keep it tightly coupled by recursively merging only the actual differences.

Extend Belgian Dutch (nl_BE) lang from Dutch (NL)

---

src/Carbon/Traits/Units.php
tests/Carbon/ModifyTest.php

This PR fixes the error `DateTime::modify(): Failed to parse time string (@1.3961412E+9.000000) at position 9 (2): Unexpected character` when calling `addRealMicrosecond()` when the INI `precision` is set too low.
It fixes the issue by casting the result of `floor()` to an integer.

Fix addRealMicrosecond() with low float precision

---

src/Carbon/Traits/Creator.php
tests/Carbon/CreateFromFormatTest.php
tests/Carbon/TestingAidsTest.php
tests/CarbonImmutable/CreateFromFormatTest.php
tests/CarbonImmutable/TestingAidsTest.php

The [documentation](http://php.net/manual/en/datetime.createfromformat.php) for `DateTime::createFromFormat()` states that "portions of the generated time which are not specified in format will be set to the current system time." However, this is has never been true for the microsecond portion, which is set to zero if not specified in the format.
There is an open ticket about this (https://bugs.php.net/bug.php?id=74332) but it doesn't appear that it will be fixed anytime soon. It seems reasonable to proceed as if the current behavior is the expected behavior for now.
Currently, the result of `Carbon::createFromFormat()` matches `DateTime::createFromFormat()` except when using test now, in which case `Carbon::createFromFormat()` returns a microsecond portion from the test now. This PR sets …

Fix createFromFormat() to match native implementation when using test now

---

src/Carbon/Traits/Difference.php
tests/Carbon/DiffTest.php
tests/CarbonImmutable/DiffTest.php

Hi there!
I experienced an issue in the Carbon\Traits\Difference::floatDiffInDays() function when the used function floatDiffInHours() is returning a decimal part.
Carbon is using the modulo operand directly. Unfortunately PHP is stripping any decimal parts beforehand and is using the numbers only as real integers:
```
php > $hoursDiff = 48.13;
php > var_dump($hoursDiff % 24);
int(0)
```
For floating-point modulo the library needs to use the php function [fmod()](https://www.php.net/manual/en/function.fmod.php).
```
php > $hoursDiff = 48.13;
php > var_dump(fmod($hoursDiff, 24));
float(0.13)
```
In this PR i changed it, added a case to the unittests and adapted all expected values in the other assertions, that are now using the decimal part as well
Cheers o/

Fix floating point modulo in floatDiffInDays() when $hoursDiff is a float

---

src/Carbon/Traits/Macro.php
tests/Carbon/Fixtures/Mixin.php
tests/Carbon/MacroTest.php

This PR fixes #1706.  Previously if your mixin had required constructor arguments it would cause a fatal error because the constructor was called with zero arguments by `Carbon::mixin`.
Similarly if you had a destructor it would also be called by `Carbon::mixin`.
I updated the `MacroTest` mixin fixture to reproduce the constructor issue.

Fix #1706 Allow mixins to have constructor arguments

---

src/Carbon/CarbonInterface.php
src/Carbon/CarbonInterval.php
tests/CarbonImmutable/DiffTest.php

This pull requests resolves #1701.
I think that the case described in the issue is not considered about the week.
This pull request is an implementation that takes the week into consideration. (although the code is actually written in the issue 👍)
We can see if we check the unit test, but here's some examples.
| diff                                      | parts | without SEQUENTIAL_PARTS_ONLY (actual result/default) | with SEQUENTIAL_PARTS_ONLY |
|-------------------------------------------|-------|-------------------------------------------------------|----------------------------|
| 2019-01-04 - 2019-02-04                   | 2     | 1 month                                               | 1 month                    |
| 2019-01-04 - 2019-02-11                   | 2     | 1 month 1 week …

Add SEQUENTIAL_PARTS_ONLY option for diffForHumans

---

src/Carbon/Carbon.php

Hi,
found and fix some mistakes in comments

[FIX] commets for $englishMonth and $shortEnglishMonth attributes

---

src/Carbon/Lang/cs.php
tests/Localization/CsCzTest.php
tests/Localization/CsTest.php

- Implement a_unit forms
- Fix hodina/hodinu, minuta/minutu, sekunda/sekundu declensions
- Use čvn/čvc to distinguish June from July

Fix #1740 Czech translation

---

.github/FUNDING.yml
.travis.yml
phpdoc.php
phpstan.neon
src/Carbon/Carbon.php
src/Carbon/CarbonImmutable.php
src/Carbon/CarbonInterface.php
src/Carbon/CarbonInterval.php
src/Carbon/CarbonPeriod.php
src/Carbon/Lang/chr_US.php
src/Carbon/Traits/Converter.php
src/Carbon/Traits/Date.php
tests/CarbonInterval/ConstructTest.php
tests/CarbonPeriod/CreateTest.php
tests/CarbonPeriod/GettersTest.php

- Add toPeriod, range and {unit}Until methods
- Add overlaps method
- Fix PHP 7.3.4 to 7.3.6 compatibility
- Interval smaller than 1 second are no longer considered empty

CarbonPeriod improvements

---

src/Carbon/Laravel/ServiceProvider.php
tests/AbstractTestCase.php
tests/Laravel/App.php
tests/Laravel/Dispatcher.php
tests/Laravel/EventDispatcher.php
tests/Laravel/EventDispatcherBase.php
tests/Laravel/ServiceProvider.php
tests/Laravel/ServiceProviderTest.php

This PR implements the changes discussed in issue #1747.
Namely, it allows `$app['events']` instances to be instances of `Illuminate\Contracts\Events\Dispatcher` in order to support any implementation of Laravel's event dispatcher.
Note that I've taken the liberty to extract the `if` condition into it's own protected method. Let me know if you'd like me to inline it instead.
Thanks again for allowing me to write this PR. 🙏

[Laravel] Support event dispatcher's contract

---

docs/index.src.html

I use Carbon too often to give nothing in return so I made some small grammatical changes to the macros documentation. I’ll continue to take a look at other areas as I find a spare hour here and there. 
I like to document when my I've wrote enough code for one day!

Small grammatical changes to macros documentation

---

.travis.yml
src/Carbon/CarbonInterval.php
tests/CarbonInterval/ParseFromLocaleTest.php

Added a `parseFromLocale` static method to the `CarbonInterval` class as requested in issue https://github.com/briannesbitt/Carbon/issues/1756
I was not 100% sure how in depth to go with the unit tests so I ended up duplicating those from the `tests/CarbonInterval/FromStringTest.php` as it really just hooks into that functionality anyway. I then added a test for the example given in the issue.

#1756 Add a parseFromLocale method to the CarbonInterval class

---

.php_cs.dist
src/Carbon/CarbonPeriod.php
tests/CarbonPeriod/ComparisonTest.php

Add CarbonPeriod methods:
- Fix #1829 Improve CarbonPeriod JSON serialization
- Implement contains()
- Implement getIncludedStartDate()
- Implement getIncludedEndDate()
- Implement follows()
- Implement isFollowedBy()
- Implement isConsecutiveWith()

Implement contains() and JsonSerializable in CarbonPeriod

---

composer.json

https://writingexplained.org/a-vs-an-difference

Fix Composer description grammar

---

src/Carbon/CarbonInterface.php

There was an error in the documentation of the function isBefore.
2018-07-25 12:45:16 is before 2018-07-25 12:45:18.

Fix isBefore documentation

---

src/Carbon/CarbonPeriod.php

There seems to be a bug in the return type annotation for `validateCurrentDate`.
This bug crashes `Psalm`.

Fix Return Type Annotation

---

src/Carbon/CarbonInterval.php
src/Carbon/Exceptions/ParseErrorException.php
tests/CarbonInterval/CreateFromFormatTest.php

Added `createFromFormat` method to `CarbonInterval`'s core for #1918 .
Useful to handle time interval strings like MySQL `time` field (e.g.: '10:20:00'):
E.g.:
```php
CarbonInterval::createFromFormat('H:i:s', '10:20:00')
```
is equivalent to:
```php
list($hours, $minutes, $seconds) = explode(':', '10:20:00');
new CarbonInterval(0, 0, 0, 0, $hours, $minutes, $seconds);
```
or
```php
CarbonInterval::hours($hours)->minutes($minutes)->seconds($seconds);
```

Add createFromFormat static method to CarbonInterval

---

src/Carbon/CarbonPeriod.php
src/Carbon/Traits/Creator.php
src/Carbon/Traits/Localization.php
tests/CarbonPeriod/ToStringTest.php

This Pull Request is in the form of Help Wanted / Possible Bug report.
I recently noticed that when using `CarbonPeriod` and Carbon, they differ in configuration of when the week start (Monday vs Sunday) causing inconsistency. I'm looking for help on validating whether there's something I can do to fix this issue or if it's actually a bug that would need to be addressed in Carbon itself.
The use case:
Parsing the date **2019-12-01** and asking for the first day of the Week, by default, returns **2019-11-25**, which is the Monday of said Week. Using CarbonPeriod to make an array of weeks will give an array of Carbon instances that are differently configured and will consider **Sunday** as the first day of the week. When asking for the first day of the week from **2019-11-25**, it further …

CarbonPeriod and CarbonImmutable not behaving similarly

---

src/Carbon/Traits/Creator.php
src/Carbon/Traits/Date.php
src/Carbon/Traits/ObjectInitialisation.php
src/Carbon/Traits/Serialization.php
tests/Carbon/SerializationTest.php

A `Carbon` object can be obtained in 3 ways:
- using the `new` keyword 
- using the `newInstanceWithoutConstructor` method
- using the `unserialize` function
I've added a new property called `isDateTimeInitialised` that will tell us if a Carbon object has been initialised or not. The only time when the object is not initialised is when the `newInstanceWithoutConstructor` is used to obtain the object. 
When setting a property, checking if the object was initialised or not is done in the `__set` method. This is simply because we need to be able to serialize imutable objects too.

Fixed serialization issue

---

src/Carbon/CarbonInterval.php
tests/CarbonInterval/ToStringTest.php

Complete with tests (second attempt).

#2002 Fix CarbonInterval not honoring toStringFormat setting.

---

tests/CarbonPeriod/CreateTest.php

Remove `expectExceptionMessageRegExp()` that is removed since PHPUnit 9 to be ready for a migration.

Remove deprecated method

---

tests/Carbon/CreateFromTimestampTest.php
tests/CarbonImmutable/CreateFromTimestampTest.php
tests/Language/TranslatorTest.php

testSetLocale fails in environments lacking the desired English locales.
Other tests that rely on specific locales being available on the system are
skipped if those locales are unavailable.
This change will similarly skip this test if the desired locale is not found.

Skip test when an English locale is unavailable

---

src/Carbon/CarbonInterface.php
src/Carbon/Traits/Difference.php
tests/Carbon/DiffTest.php

There currently is no method for getting the difference in quarters of 2 carbon objects. Whereas there are methods for adding and subtracting quarters. This PR implements the "missing" method.

Add method for diffInQuarters

---

src/Carbon/Lang/de_AT.php

Fix #2036 Short month January translation in de_AT

---

composer.json
phpunit.xml.dist
src/Carbon/Doctrine/CarbonType.php
src/Carbon/Doctrine/DateTimeDefaultPrecision.php
src/Carbon/Doctrine/DateTimeImmutableType.php
src/Carbon/Doctrine/DateTimeType.php
tests/Carbon/SettersTest.php

Doctrine ORM (and so Symfony) provides `datetime` and `datetime_immutable` types for `DateTime` and `DateTimeImmutable`.
This PR provides Doctrine types to get dates properties automatically mapped to `Carbon` and `CarbonImmutable` so Symfony users could choose to get every entities dates enhanced with `Carbon` methods (or use a custom type name to enable it on demand).
Usage: add types to **config/packages/doctrine.yaml**:
```yaml
doctrine:
dbal:
types:
datetime_immutable: \Carbon\Doctrine\DateTimeImmutableType
datetime: \Carbon\Doctrine\DateTimeType
```
Credits: https://github.com/doctrine/dbal/issues/2873#issuecomment-534956358
To be noted:
- This implementation will also allow to set a custom precision for a given property using annotation: `ORM\Column(type="datetime", precision=3)` …

#2041 Provide Doctrine ORM Carbon types

---

src/Carbon/Doctrine/CarbonType.php

Hello, 
When I tried the new carbon type, I got a "Data missing".
This is due to postgres not using the 'Y-m-d H:i:s.u' format but 'Y-m-d H:i:s' when microseconds are set to zero.
The solution is based on this comment :
https://github.com/doctrine/dbal/issues/2873#issuecomment-535452749

Fix doctrine orm carbon type

---

composer.json

Since Carbon is using mb_ functions this should be in the composer.json to make sure the mbstring extension is installed. 
(And also, for my personal sanity when browsing the code in PHPStorm)

Add ext-mbstring to requirements

---

tests/Carbon/LocalizationTest.php
tests/CarbonImmutable/LocalizationTest.php

Avoids a test failure because of "Expected: 'ar' Actual: 'ar_AE'".
It corresponds to the approach to 'sr' and 'zh' in the same test.

Accept ar_AE in localization test

---

src/Carbon/Traits/Rounding.php

The current update of Larastan started emitting a new error (as reported here https://github.com/nunomaduro/larastan/issues/541). Making the method signature consistent with the Interface could fix the problem.

Fix static analyses of Carbon

---

src/Carbon/Lang/ka.php
tests/Localization/KaGeTest.php
tests/Localization/KaTest.php

- Typo: replace `კვირი` with `კვირა` causing incorrect translation.
- Grammar: both "ago" and "before" in Georgian is "წინ". The word "უკან" means *behind*, not *before* and is grammatically incorrect.

Georgian typo and grammar

---

readme.md

This PR adds an opening php tag in order to have the syntax highlighting in the README.md
**Before:**
**After:**

Add php tag for syntax highlighting in README.md

---

src/Carbon/CarbonTimeZone.php
tests/CarbonTimeZone/ConversionsTest.php

Enable to find some timezones `timezone_name_from_abbr()` is not able to find.

Fix #2101 iterate over every timezone to find it

---

composer.json
phpdoc.php
phpstan.neon
src/Carbon/Carbon.php
src/Carbon/CarbonConverterInterface.php
src/Carbon/CarbonImmutable.php
src/Carbon/CarbonInterface.php
src/Carbon/CarbonInterval.php
src/Carbon/CarbonPeriod.php
src/Carbon/Traits/IntervalStep.php
src/Carbon/Traits/Units.php
tests/Carbon/AddTest.php
tests/Carbon/SubTest.php
tests/CarbonImmutable/AddTest.php
tests/CarbonImmutable/SubTest.php
tests/CarbonInterval/AddTest.php
tests/CarbonPeriod/DynamicIntervalTest.php
tests/Fixtures/dynamicInterval.php

This allow to use `Closure`'s as intervals:
```php
$weekDayStep = function (Carbon $date, bool $negated = false): Carbon {
if ($negated) {
return $date->previousWeekDay();
}
return $date->nextWeekDay();
};
Carbon::now()->add($weekDayStep); // call nextWeekDay
Carbon::now()->sub($weekDayStep); // call previousWeekDay
CarbonInterval::create($weekDayStep); // create a virtual interval representing 1 week day
CarbonPeriod::create('2020-06-01', $weekDayStep, '2020-06-14'); // iterate over every week days from June 1st to June 14th
```

Implement dynamic intervals

---

.gitattributes

Update `.gitattributes` `export-ignore` rules
- Remove `.codecov.yml` that is no longer used.
- Add `.multi-tester.yml` file
- Add `.github` directory.
- Fix alignments in all `export-ignore` rules.
Thank you 🙏🏿.

Update .gitattributes export-ignore rules

---

src/Carbon/PHPStan/MacroScanner.php
tests/PHPStan/MacroExtensionTest.php

If the variable `$className` is `CarbonInterface::class` itself or an abstract class that hasn't implemented the `getMethod` method yet, it will throw an error `Cannot call abstract method Carbon\CarbonInterface::hasMacro()`

Fix "Cannot call abstract method Carbon\CarbonInterface::hasMacro()" error

---

src/Carbon/Lang/et.php

This PR updates Estonian ISO date formats based on [CLDR data](https://github.com/unicode-cldr/cldr-dates-full/blob/204e99e8b28a52239bb6de1bbc89986cb19c0d50/main/et/ca-gregorian.json#L309-L314) current at the time of this PR. 
I'm submitting a PR because formats cannot be suggested using the translation tool.

🌎 Fix Estonian date formats based on CLDR data

---

src/Carbon/CarbonInterface.php
src/Carbon/Traits/Test.php
tests/Carbon/TestingAidsTest.php
tests/CarbonImmutable/TestingAidsTest.php

This is similar to the internal testing helper "wrapWithTestNow" but meant to be publicly accessible to outside tests

Adds a testing method called withTestNow

---

src/Carbon/Lang/es.php
src/Carbon/Lang/es_MX.php

As mentioned in the issue #2238 , I've replaced the use of "antier" by "anteayer" in the generic spanish translation, and moved "antier" to mexican spanish translation.

Fix use of "anteayer" and "antier" in spanish translations

---

src/Carbon/CarbonInterval.php
src/Carbon/CarbonPeriod.php
src/Carbon/Traits/Mixin.php
tests/CommonTraits/MacroContextNestingTest.php

Allow to know from a mixin if the call is static or on an instance:
```php
Carbon::macro('getContext', static function () {
return static::context();
});
Carbon::getContext(); // null
$date = Carbon::parse('2020-12-10');
$date->getContext(); // $date
```

Implement context() method

---

src/Carbon/Lang/hr.php

This is the official croatian date writing.
e.g. today is 29. 1. 2021.

Update croatian date format (hr)

---

src/Carbon/CarbonInterval.php
tests/AbstractTestCase.php
tests/CarbonInterval/AddTest.php
tests/Laravel/App.php

Fix #2089
- Add methods `addYears()`, `addMonths()`, ... `addMicroseconds()` taking integer (or float value for units from week to microseconds)
```php
echo CarbonInterval::days(2)->addWeeks(1)->addDays(1.5); // 1 week 3 days 12 hours
```
- Add methods `subYears()`, `subMonths()`, ... `subMicroseconds()` taking integer (or float value for units from week to microseconds)
```php
echo CarbonInterval::weeks(2)->subWeeks(1)->subDays(4); // 3 days
```
- Add methods `plus()` and `minus()` taking `$years`, `$months`, `$weeks`, `$days`, `$hours`, `$minutes`, `$seconds`, `$microseconds` as parameters:
```php
echo CarbonInterval::days(2)->plus(0, 0, 1, 1.5); // 1 week 3 days 12 hours
```
Thanks to PHP 8 named arguments, it can provide an neat way to pick units in any order:
```php
echo …
```

Add plus() and minus() methods to CarbonInterval

---

src/Carbon/Traits/Creator.php

In order to make static analysis tools happier (PHPStan at least)

Makes PHPDoc consistent

---

src/Carbon/Traits/Creator.php

This is just a minor readability improvement.  
We already know that `$var` is a string ([`trim`](https://www.php.net/manual/en/function.trim.php) always returns a string), so there's no need for additional check.

Remove unnecessary check within `make` method

---

src/Carbon/CarbonInterval.php
src/Carbon/CarbonPeriod.php
tests/Laravel/App.php

Passing null to non-nullable arguments of internal functions has been deprecated in PHP 8.1 ([RFC](https://wiki.php.net/rfc/deprecate_null_to_scalar_internal_arg)).

Fix passing null to non-nullable arguments

---

.php_cs.dist
.styleci.yml
src/Carbon/Doctrine/CarbonTypeConverter.php
src/Carbon/Doctrine/DateTimeImmutableType.php
src/Carbon/Doctrine/DateTimeType.php

This PR's purpose is to allow [phpstan-doctrine](https://github.com/phpstan/phpstan-doctrine) to recognise `Carbon`|`CarbonImmutable` and `carbon`|`carbon_immutable` usages in entities. The main beneficiaries of this are those using the library in a Symfony project with Doctrine.
- this was recommended as the best approach by @ondrejmirtes here: https://github.com/phpstan/phpstan-doctrine/pull/192#issuecomment-850258319
- I tested and this will work with both ways of using this library with Doctrine if all types are registered in phpstan-doctrine, i.e:
A)
```
datetime_immutable: \Carbon\Doctrine\DateTimeImmutableType
datetime: \Carbon\Doctrine\DateTimeType
```
B)
```
carbon_immutable: \Carbon\Doctrine\CarbonImmutableType
carbon: \Carbon\Doctrine\CarbonType
```

Add Doctrine Types Annotations

---

src/Carbon/CarbonInterval.php
src/Carbon/Traits/Creator.php
src/Carbon/Traits/Units.php

- Drop [PHP <= 7.2 bug fix 77007](https://bugs.php.net/bug.php?id=77007)
- Drop [PHP <= 7.2 bug fix 77145](https://bugs.php.net/bug.php?id=77145)
- Drop [PHP <= 7.1 bug fix 67127](https://bugs.php.net/bug.php?id=67127)
- Drop [PHP <= 7.2 bug fix 75642](https://bugs.php.net/bug.php?id=75642)

Drop fixes for old PHP versions

---

src/Carbon/Lang/pl.php

It seems that PL translations provide 3 variants, depending on `:count` param value, but the "short year" translation provides only two, which causes a runtime error.
I don't know PHP, so I am not able to provide (in reasonable time) reproduction steps other than the actual use where I spotted the problem. Sample manifestation of the bug is described in the following issue:
https://github.com/firefly-iii/firefly-iii/issues/4845

Fix polish translation causing a runtime error

---

src/Carbon/Traits/Test.php
tests/Carbon/TestingAidsTest.php
tests/CarbonImmutable/TestingAidsTest.php

Title says it all. This makes it just slightly more useful. Sometimes just the creation of a thing relies on a static date.

Use the return value from callback in withTestNow

---

docs/index.src.html

Add space into `agoor` and ` beforeor`.

Add space into diffForHumans modifier

---

src/Carbon/CarbonInterface.php
src/Carbon/CarbonPeriod.php
src/Carbon/Lang/nl.php
src/Carbon/Lang/oc.php
src/Carbon/Language.php
src/Carbon/Traits/Date.php
src/Carbon/Traits/Localization.php

Since my PR #2338 return types have also been added to `JsonSerializable::jsonSerialize()`.
I've also fixed a few cases of passing null to non-nullable arguments that I've missed in #2337.

Fixes for PHP 8.1

---

.php_cs.dist
.styleci.yml
build.php
phpdoc.php
tests/AbstractTestCase.php
tests/Carbon/ArraysTest.php
tests/Carbon/CreateStrictTest.php
tests/Carbon/GettersTest.php
tests/Carbon/InstanceTest.php
tests/Carbon/LocalizationTest.php
tests/Carbon/MacroTest.php
tests/Carbon/SettersTest.php
tests/CarbonImmutable/GettersTest.php
tests/CarbonImmutable/InstanceTest.php
tests/CarbonImmutable/LocalizationTest.php
tests/CarbonImmutable/MacroTest.php
tests/CarbonInterval/ToDateIntervalTest.php
tests/CarbonPeriod/CloneTest.php
tests/CarbonPeriod/CreateTest.php
tests/CarbonPeriod/DynamicIntervalTest.php
tests/CarbonPeriod/IteratorTest.php
tests/CarbonPeriod/MacroTest.php
tests/CarbonPeriod/ToDatePeriodTest.php
tests/CarbonTimeZone/ConversionsTest.php
tests/CommonTraits/MacroContextNestingTest.php
tests/Jenssegers/JenssegersDate.php
tests/Language/LanguageTest.php
tests/Localization/LanguagesCoverageTest.php
tests/Localization/NlTest.php

This PR cleans up  .styleci.yml and .php_cs.dist files.
This PR also enforces the same code-style on the whole project and not only `/src` while running php-cs-fixer.
as `.styleci.yml` already covers on the whole project (also `/tests`).
(See 964c15f8bb9b109ebfcce3a927920f4c19a353dc)

Clean-up .styleci.yml and .php_cs.dist

---

.php_cs.dist
.styleci.yml
src/Carbon/CarbonInterval.php
src/Carbon/Traits/Comparison.php
src/Carbon/Traits/Date.php
src/Carbon/Traits/Difference.php
src/Carbon/Traits/Timestamp.php
src/Carbon/Traits/Units.php
tests/Carbon/GettersTest.php
tests/CarbonImmutable/GettersTest.php
tests/CarbonPeriod/CloneTest.php
tests/CarbonTimeZone/ConversionsTest.php
tests/CommonTraits/MacroContextNestingTest.php
tests/Language/LanguageTest.php
tests/Localization/NlTest.php

This PR add a new rule to `php-cs-fixer` and `styleci` in order to modernize  the types casting.

Modernize type casting.

---

src/Carbon/Traits/Creator.php
src/Carbon/Traits/Date.php
src/Carbon/Traits/Localization.php
src/Carbon/Traits/Modifiers.php
src/Carbon/Traits/Serialization.php
src/Carbon/Traits/Units.php

Use type-casting instead of double-quoting the variable

Use type-casting.

---

.php_cs.dist
.styleci.yml
src/Carbon/CarbonInterval.php
src/Carbon/CarbonPeriod.php
src/Carbon/CarbonTimeZone.php
src/Carbon/Traits/Date.php

`null` comparisons are checked with `===` and `!==` everywhere in the code, which is faster than using `is_null` function.
Only those `is_null` calls were remaining.
This PR enforces consistency and remove them.

Enforce consistency and stop using is_null.

---

tests/Carbon/ConstructTest.php
tests/Carbon/CreateSafeTest.php
tests/Carbon/StrictModeTest.php
tests/CarbonInterval/StrictModeTest.php
tests/CarbonPeriod/StrictModeTest.php
tests/CarbonTimeZone/ConversionsTest.php

This PR gets rid of useless calls to `useStrictMode` static function.

Gets rid of useless calls to useStrictMode()

---

tests/Jenssegers/TestCaseBase.php

This PR fixes `TestBaseCase`:
- No tests are executed, so the class should be abstract
- No override of setUp is recommended
- As a good practice, the parent setUp should always be called.

Fix TestBaseCase

---

src/Carbon/CarbonInterface.php

This was added in https://github.com/briannesbitt/Carbon/pull/2364 and then removed in 865611d45f116ff00b8b584bd37a1c8e4e6fc4b9. I think this was removed accidentally as there's a deprecation notice when running PHP 8.1:
> Return type of Carbon\CarbonInterface::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor/nesbot/carbon/src/Carbon/CarbonInterface.php:3025

Add `ReturnTypeWillChange` to `CarbonInterface::jsonSerialize`

---

src/Carbon/Traits/Timestamp.php
tests/Carbon/NowAndOtherStaticHelpersTest.php
tests/CarbonImmutable/NowAndOtherStaticHelpersTest.php

Hi there! Firstly, thank you for your continued work on Carbon, I don't know what I'd do without it! 
This PR adds a new `getTimestampMs()` method to compliment the already existing `createFromTimestampMs()` method. 
This is mostly a helper method to easily return a millisecond-precise timestamp as an `integer`. It also reads more naturally than the currently available methods (which return a `float`):
**Before**
```php
$timestamp = (int) $carbonDate->getPreciseTimestamp(3);
// OR
$timestamp = (int) $carbonDate->valueOf();
```
**After**
```php
$timestamp = $carbonDate->getTimestampMs();
```
Please let me know if there's any questions or feedback. I'm also happy to submit a PR to the docs if this gets merged.
Thanks!

Add getTimestampMs method to output millisecond-precise timestamps

---

.gitattributes
codecov.yml

This PR disables the coverage report comment report for each PR.
IMO having access to hit via the PR status and the README badge is already sufficient.

Stop displaying coverage report for each PR

---

src/Carbon/Translator.php

This fixes an issue introduced by Symfony\Translate v4.4.27 changing the default return value of `getLocale()` to fallback to `\Locale::getDefault()` when php-intl is installed and enabled; and `'en'` when it is not. 
Previously, a newly initialized `Translator` object would have returned `null` from `getLocale()` on first initialization, which would have made this check pass. However, this change now means that the initialization that is supposed to occur from a fresh Translator calling setLocale() on itself will fail under the following conditions:
- The locale being initialized matches the one returned by `\Locale::getDefault()` on systems with php-intl installed and enabled
- Or the locale being initialized is `en` on systems where php-intl is not installed or enabled.
See …

Fix issue with Symfony\Translate v4.4.27

---

.php-cs-fixer.dist.php

Add `no_extra_consecutive_blank_lines` rule to `php-cs-fixer` 
( as for now duplicate empty lines are not removed )
---
_Note:_
This rule is already set in StyleCI and cannot be re-added ( cf. https://github.styleci.io/analyses/0gaB74 )

Add no_extra_consecutive_blank_lines rule to php-cs-fixer

---

src/Carbon/Lang/pl.php
tests/Localization/PlPlTest.php
tests/Localization/PlTest.php

Remove period from "min" (minute) in Polish

---

tests/Carbon/AddMonthsTest.php
tests/Carbon/CreateTest.php
tests/Carbon/GettersTest.php
tests/Carbon/IsTest.php
tests/Carbon/IssetTest.php
tests/Carbon/LocalizationTest.php
tests/Carbon/ModifyNearDSTChangeTest.php
tests/Carbon/SerializationTest.php
tests/Carbon/SettersTest.php
tests/Carbon/StartEndOfTest.php
tests/CarbonImmutable/IsTest.php
tests/CarbonImmutable/ModifyNearDSTChangeTest.php
tests/CarbonInterval/AddTest.php
tests/CarbonInterval/CascadeTest.php
tests/CarbonInterval/FromStringTest.php
tests/CarbonInterval/ParseFromLocaleTest.php
tests/CarbonInterval/ToPeriodTest.php
tests/CarbonInterval/TotalTest.php
tests/CarbonPeriod/CreateTest.php
tests/CarbonPeriod/IteratorTest.php
tests/CarbonPeriod/ToStringTest.php
tests/CarbonTimeZone/ConversionsTest.php
tests/CommonTraits/MacroContextNestingTest.php
tests/Doctrine/CarbonTypesTest.php
tests/Laravel/ServiceProviderTest.php

Use generators for dataProviders.
This is especially way more memory-efficient when dealing with large arrays.

Use generators for test data providers 

---

src/Carbon/CarbonInterval.php
src/Carbon/CarbonPeriod.php
src/Carbon/Factory.php
src/Carbon/Traits/Creator.php
src/Carbon/Traits/Date.php
src/Carbon/Traits/Options.php
tests/Carbon/SettersTest.php
tests/CarbonImmutable/SettersTest.php
tests/CarbonInterval/ToPeriodTest.php
tests/CarbonPeriod/CreateTest.php
tests/CarbonPeriod/SettersTest.php
tests/Factory/FactoryTest.php

Improve factory timezone handling

---

src/Carbon/Traits/Difference.php
tests/Carbon/DiffTest.php
tests/CarbonImmutable/DiffTest.php

- Add unit test for PHP bug 80974 to prove the work-around is still needed in Carbon 2.x
- Restore the work-around

Add unit test for PHP bug 80974

---

phpunit.xml.dist

This PR fixes `phpunit` syntax warning:
```
> php -d memory_limit=-1 -d zend.enable_gc=0 vendor/bin/phpunit
PHPUnit 8.5.20 by Sebastian Bergmann and contributors.
Warning - The configuration file did not pass validation!
The following problems have been detected:
Line 6:
- Element 'phpunit', attribute '{https://www.w3.org/2001/XMLSchema-instance}noNamespaceSchemaLocation': The attribute '{https://www.w3.org/2001/XMLSchema-instance}noNamespaceSchemaLocation' is not allowed.
Test results may not be as expected.
```

Fix phpunit syntax warning

---

.php-cs-fixer.dist.php
src/Carbon/CarbonInterface.php
src/Carbon/CarbonInterval.php
src/Carbon/Traits/Test.php
tests/Carbon/Exceptions/NotLocaleAwareExceptionTest.php

This PR enforces docblock alignment consistancy with `phpdoc_align` rule.

Enforce docblock alignment consistancy with phpdoc_align rule

---

src/Carbon/CarbonInterface.php
src/Carbon/Doctrine/CarbonImmutableType.php
src/Carbon/Doctrine/CarbonType.php
src/Carbon/Doctrine/CarbonTypeConverter.php
src/Carbon/PHPStan/Macro.php
src/Carbon/Traits/Creator.php
src/Carbon/Traits/Modifiers.php
src/Carbon/Traits/Serialization.php

This package included almost all `@return` PHPdoc except from a few. Some of these have comments that were `{@inheritdoc}`, but given the "inheritdoc" are from PHP's `DateTimeInterface`, one could argue that they are "unknown".
Besides fixing the PHPdoc, these return annotations will also suppress type deprecations when Carbon is used in a Symfony application. Since Symfony 5.4, developers are warned when a child class does not yet have a return type (PHP native or PHPdoc) while the parent has. See also [the Symfony docs](https://symfony.com/doc/5.4/setup/upgrade_major.html#upgrading-to-symfony-6-add-native-return-types) for more info on this topic.
I'm not sure about the plans of Carbon to add PHP typing (I saw that 7.1 compat is still maintained, so I expect it'll take a while), but I …

Add `@return` PHPdoc to `{@inheritdoc}` blocks from vendors

---

src/Carbon/Traits/Difference.php
tests/Carbon/IsTest.php
tests/CarbonImmutable/IsTest.php

Bug 80998 is fixed but we need to keep the work-around because of:
https://bugs.php.net/bug.php?id=81458

Document bug 81458

---

src/Carbon/Lang/lv.php

Changed short names based on legislation "Par mēnešu nosaukumu saīsinājumiem latviešu valodā"
Fix #2479

LV month short names from legislation

---

src/Carbon/Lang/pl.php
src/Carbon/Lang/szl_PL.php
tests/Localization/SzlPlTest.php
tests/Localization/SzlTest.php

Replace Polish ending in grouped units

---

src/Carbon/CarbonPeriod.php
tests/CarbonPeriod/CreateTest.php

Fixes #2527.
The regular expression to parse the recurrence is augmented with the INF value. Based on this, the recurrence value is set to INF, if RINF is found.

CarbonPeriod Handle infinite recurrences when parsing period string

---

src/Carbon/Doctrine/CarbonTypeConverter.php
tests/Doctrine/CarbonTypesTest.php

Allow explicitly defined 0 precision for DBAL types without explicitly setting Datetime precision through `DateTimeDefaultPrecision::set()` because right now explicit 0 precision is treated same as `null`.

Allow precision 0 in Carbon DBAL types

---

src/Carbon/Lang/fr.php

French needs to be capitalized when not used as verb.
Past participle issue or typo in same line "be" should be "been"

Grammar fixes

---

.github/workflows/tests.yml
composer.json
phpunit.xml.dist
src/Carbon/Lang/en.php
src/Carbon/Lang/ss.php
src/Carbon/Lang/sv.php
src/Carbon/Traits/Date.php
tests/Carbon/GettersTest.php
tests/Carbon/IssetTest.php
tests/Carbon/StringsTest.php
tests/CarbonImmutable/IssetTest.php
tests/CarbonImmutable/StringsTest.php
tests/Laravel/App.php
tests/bootstrap.php

Fix PHP 8.1 deprecations

---

tests/Carbon/DiffTest.php
tests/CarbonImmutable/DiffTest.php

PHPUnit 9.5.14 increased the precision of float comparisons from
0.0000000001 to PHP_FLOAT_EPSILON, causing some tests to fail.

Improve float comparison precision in tests

---

tests/Carbon/CreateFromTimeTest.php
tests/CarbonImmutable/CreateFromTimeTest.php

In the test when timezone is specified, `Carbon::now()` is used to calculate the expected date. If the test is run in an environment that defaults to a timezone other than the 'Europe/London' specified in the test, the test may fail because the dates obtained will be different for some hours of the day.
Specifying the time zone when asking for the expected date solves this problem.

Fix CreateFromTimeTest

---

src/Carbon/Traits/Test.php
tests/Carbon/TestingAidsTest.php
tests/CarbonImmutable/TestingAidsTest.php

Moved `setTestNow()` to the `finally` clause so that `setTestNow()` is executed even if `$callback()` throws an exception.
Fix #2561

Reset testNow after exceptions occurring in setTestNow()

---

src/Carbon/CarbonInterface.php

Hello,
I would like to be able to use `Carbon::QUARTERS_PER_YEAR` instead of a magic `4` number (or custom constant) on my code.
This simple PR adds the constant to the `CarbonInterface`.

Add QUARTERS_PER_YEAR constant

---

src/Carbon/CarbonPeriod.php
src/Carbon/Traits/Serialization.php
tests/CarbonPeriod/MacroTest.php

This PR enforces `::class` notation.

Enforce ::class notation

---

src/Carbon/Traits/Test.php
tests/Carbon/TestingAidsTest.php
tests/CarbonImmutable/TestingAidsTest.php

This PR provides the ability to use \DateTimeInterface as the argument type for the Test::setTestNow() method.
Currently this method can receive instances of CarbonInterface, but cannot receive instances of \DateTime and \DateTimeImmutable php-classes exactly.
Support for \DateTime and \DateTimeImmutable types will provide more flexibility for client code.

Add \DateTime and \DateTimeImmutable support to the Test::setTestNow()

---

.github/workflows/tests.yml

This PR caches the composer dependencies with a Github action.
---
The key takes in consideration the PHP version, the desired composer stability setup, the OS and the `composer.json` file.
There is always the possibility to manually run the tests without cache

Cache composer dependencies with a Github action

---

src/Carbon/Traits/Units.php

This PR removes useless `break;` keywords.

Remove useless break

---

.github/workflows/phpcs.yml
src/Carbon/CarbonPeriod.php
src/Carbon/Traits/Converter.php
src/Carbon/Traits/Creator.php
src/Carbon/Traits/Date.php
src/Carbon/Traits/Localization.php
src/Carbon/Traits/Timestamp.php
src/Carbon/Traits/Units.php

This PR adds parenthesis for ease up the understanding of conditions priorities.

Add parenthesis for ease up the understanding of conditions priorities

---

tests/CarbonInterval/CreateFromFormatTest.php

Use `expectExceptionObject` assertion for consistency.

Use expectExceptionObject assertion for consistency.

---

src/Carbon/Traits/Date.php

PHP 8.2 deprecates the use of the `${var}` interpolation pattern in favor of `{$var}`. This PR fixes deprecated occurrences to use the  other syntax.
Reference: https://wiki.php.net/rfc/deprecate_dollar_brace_string_interpolation

Fix deprecated ${var} string interpolation patterns (PHP 8.2)

---

src/Carbon/Traits/Date.php
tests/Carbon/StringsTest.php
tests/CarbonImmutable/StringsTest.php

Closes #2630
>`utf8_encode()` deprecated
https://php.watch/versions/8.2/utf8_encode-utf8_decode-deprecated

Fix Php 8.2 utf8_encode deprecation

---

src/Carbon/Laravel/ServiceProvider.php

When an Octane server is starts, we boot the framework once. After, every time Octane serves a request, it uses a "clone" of that application instance used to boot framework to serve that request. 
This is done, so any change made to that "cloned" application instance does not impact the original application instance and specially does not get propagated to the next request - similar to a regular PHP FPM implementation where requests are served always using a fresh application instance.
Now, currently, Carbon's service provider is capturing a reference to the original application instance, the one we use to "clone" an application for every new request. Meaning the following:
Before this pull request:
```php
// Users do:
app()->setLocale("pt"); // Change the state of the request …
```

Fixes updating locale when app instance changes in Octane

---

src/Carbon/CarbonInterval.php
tests/CarbonInterval/SpecTest.php

https://www.postgresql.org/docs/14/datatype-datetime.html#DATATYPE-INTERVAL-INPUT
Postgres date interval field values can have fractional parts.
https://tc39.es/proposal-temporal/docs/duration.html
Also see the `ECMAScript` Temporal Proposal : `duration.toString` has a `fractionalSecondDigits` option

Add options for microseconds on getDateIntervalSpec()

---

src/Carbon/Traits/Creator.php
tests/Carbon/LastErrorTest.php
tests/CarbonImmutable/LastErrorTest.php

`DateTime::lastErrors` can return either an array or false. Right now, while testing PHP 8.2 on Laravel we discovered there's a type mismatch here on the `setLastErrors` that doesn't takes `false` into account. I've removed the type-hint because union types aren't supported yet for all PHP versions this library supports. Instead, type checks are now done inside the method. If we get `false`, we clear the `$lastErrors` property.
See failing tests in Laravel right now:
```
2022-09-01T13:53:42.6921975Z 676) Illuminate\Tests\Integration\Database\EloquentPaginateTest::testPaginationWithDistinct
2022-09-01T13:53:42.6922324Z TypeError: Carbon\CarbonImmutable::setLastErrors(): Argument #1 ($lastErrors) must be of type array, bool given, called in …
```

Fix PHP 8.2 issue with false for lastErrors

---

src/Carbon/CarbonInterval.php
src/Carbon/CarbonPeriod.php
src/Carbon/Traits/Converter.php
src/Carbon/Traits/ToStringFormat.php
tests/CarbonInterval/ToStringTest.php
tests/CarbonPeriod/ToStringTest.php

Use the same possibility and precedence for `->settings(['toStringFormat' => ...])`, `::setToStringFormat()` then default cast method for all `Carbon`, `CarbonImmutable`, `CarbonInterval` and `CarbonPeriod`.
`::setToStringFormat()` remains discouraged for all classes and `->settings(['toStringFormat' => ...])` (with or without factory) is still the safest option.
But for consistency, until 3.0, they'll be aligned across the different classes.
Resolves #2656

Harmonize toStringFormat config

---

src/Carbon/Traits/Units.php

Since PHP 7.0, functions inspecting arguments, like func_get_args(), no longer report the original value as passed to a parameter but will instead provide the current value. 
The parameter `$unit` was changed in previous lines. So the exception message contains the changed value. 
I assume that it is nicer to print the original values so that the user of the library knows which value caused the issue.
This PR preserves the original arguments in a variable to be eventually used in the error message.

Print original params in Carbon\Traits\Units::addUnit error message

---

src/Carbon/CarbonInterval.php

Added case 'yr', 'yrs' and 'mos'.
Fix #2678

Added case 'yr', 'yrs' and 'mos' alias in CarbonInterval string parser

---

src/Carbon/Lang/sl.php
tests/Localization/SlSiTest.php
tests/Localization/SlTest.php

Hello! I'm requesting to push this simple fix for Slovenian language: "pred 2 letoma" (2 years ago) is correct while "pred 2 leti" is wrong.
It is a common mistake and also explained here (in our language of course):
https://svetovalnica.zrc-sazu.si/topic/5955/kako-je-prav-pred-dvema-letoma-ali-pred-dvemi-leti

Update SL language ("2 years ago" translation)

---

src/Carbon/Lang/de.php
src/Carbon/Lang/es.php
src/Carbon/Lang/fr.php
src/Carbon/Lang/it.php
src/Carbon/Lang/pt.php
src/Carbon/Traits/Localization.php
tests/Jenssegers/DateTest.php

Translate ordinal word when parsing string

---

composer.json

Doctrine DBAL 3.x before 3.1.4 allows SQL Injection: https://www.cve.org/CVERecord?id=CVE-2021-43608

FIX vulnerability CVE-2021-43608

---

src/Carbon/Traits/Creator.php
tests/Carbon/CreateTest.php
tests/CarbonImmutable/CreateTest.php

Translate escaped word in `createFromLocaleFormat()`

---

src/Carbon/Traits/Creator.php

I noticed in Laravel that I got a type error when we tried to pass a `DateTimeInterface` in this method for the first argument. The code underneath seems to allow it so I thought it would be good to add it to the param's list of allowed types. I hope I got the styling right.
See https://github.com/laravel/framework/blob/a67043763ef330015acc1ffe45ba6302a648389c/src/Illuminate/Console/Scheduling/ScheduleListCommand.php#L178-L182

Add allowed type to create method

---

.phpstorm.meta.php

Hey! This file will be statically analyzed by PhpStorm and results will be used to enrich auto-completion experience in the IDE while working with the library (see https://www.jetbrains.com/help/phpstorm/ide-advanced-metadata.html#expected-arguments for extensive documentation on the syntax).
Similar files are existing in other packages in different form, for instance, in PHPUnit: https://github.com/sebastianbergmann/phpunit/blob/main/.phpstorm.meta.php

Provide basic completion assistance in PhpStorm

---

tests/CarbonInterval/RoundingTest.php

The exit call breaks the test suite by exiting PHPUnit. These calls are presumably just unintentional leftovers of development.

Remove exit call in unit tests

---

phpstan.neon
readme.md
src/Carbon/CarbonInterval.php
src/Carbon/Traits/Creator.php
src/Carbon/Traits/Units.php
tests/Carbon/ModifyTest.php
tests/Fixtures/DateMalformedIntervalStringException.php
tests/Fixtures/DateMalformedStringException.php

- Catch `DateMalformedIntervalStringException`
- Catch `DateMalformedStringException`

Fix PHP 8.3 compatibility

---

src/Carbon/Lang/en_CH.php
tests/Localization/EnChTest.php

In Switzerland, we will always use the `DD.MM.YYYY` format.

Update en_CH formats

---

src/Carbon/Traits/Difference.php
tests/Carbon/DiffTest.php
tests/CarbonImmutable/DiffTest.php

Enforce diffInWeekdays and diffInWeekendDays to use perdiod starting and ending at the same hour
Fix #2798

Fix diffInWeekdays and diffInWeekendDays with partial days

---

phpstan.neon
src/Carbon/Traits/Creator.php

Clone DateTime not to mutate them on construction

---

src/Carbon/Lang/sl.php
tests/Localization/SlSiTest.php
tests/Localization/SlTest.php

Dual for month was wrong.
Reference: https://www.leemeta.si/blog/jezikovne-dileme/5-najpogostejsih-napak-pri-rabi-dvojine

Fix dual for month in Slovenian language

---

.github/workflows/tests.yml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Use env var to pass composer cache config in GitHub Actions

---

.github/workflows/tests.yml
src/Carbon/MessageFormatter/MessageFormatterMapper.php
src/Carbon/Traits/Localization.php

… Climate Test Reporter
fix ci deprecation for codecov V1 => V3
https://github.com/marketplace/actions/codecov
The change from xdebug to pcov (and only one coverage output file) speed the coverage run up from > 8:32 minutes to  1:15 minutes
Example of xdebug: https://github.com/briannesbitt/Carbon/actions/runs/6021629511/job/16336221316
Example of pcov: https://github.com/Chris53897/Carbon/actions/runs/6024021872/job/16341911483
But needs testing if CodeCov works correct and Code Climate starts to work.
@kylekatarnls This can only be done from maintainers. As i got the warning/error for the missing secret ;)
Code climate does not work in the past, if we can trust the warning, that it could not find the clover.xml (because it was coverage.xml before). And it it not possible to set the …

Upgrade codecov V1 => V3 and switch to pcov

---

src/Carbon/CarbonPeriod.php

(merging options if automatically set the mutability option)
Fix #2853

Allow to set options at least one per construction

---

src/Carbon/Lang/sk.php
tests/Localization/SkSkTest.php
tests/Localization/SkTest.php

a found out inconsistencies and missing translations in slovak language. so here is a fix

fix slovak translations

---

tests/AbstractTestCase.php

before this PR, PHPStan did not narrow the type of the arg given to e.g. `assertInstanceOfCarbon`
example taken from [ToArrayTest](https://github.com/briannesbitt/Carbon/blob/77eb7b390ba15b05d201c657c080280cbcf6780c/tests/CarbonPeriod/ToArrayTest.php#L99C1-L99C1):
```php
\PHPStan\dumpType($date); // line 100
$this->assertInstanceOfCarbon($date ?? null);
\PHPStan\dumpType($date); // line 102
```
before this PR
```
------ ------------------------------------------ 
Line   ToArrayTest.php                           
------ ------------------------------------------ 
100    Dumped type: Carbon\CarbonInterface|null  
102    Dumped type: Carbon\CarbonInterface|null  
------ ------------------------------------------ 
```
after this PR
```
------ ------------------------------------------ 
Line …
```

Narrow phpstan types in assertInstanceOf* AbstractTestCase methods

---

src/Carbon/CarbonPeriod.php
src/Carbon/CarbonPeriodImmutable.php

Use relevant class to synchronize CarbonPeriod mock with Carbon and CarbonImmutable accordingly
Fix #2874

Use relevant class to synchronize CarbonPeriod mock

---

src/Carbon/Traits/Rounding.php
tests/Carbon/RoundTest.php
tests/CarbonImmutable/RoundTest.php

I was having a problem that looked a bit like #2268.
When rounding down to quarters, the month overflows when a date is after a possible date of the rounded month. This PR causes the changes to be applied before the main unit is changed, so the day is set before the month.
You can see an example in the tests. When rounding down months by a precision of 3, the 31st of may now becomes the 1st of april, instead of the 1st of may.

fix(Rounding): apply rounding changes to result before applying unit

---

src/Carbon/Lang/hu.php

Fix Hungarian translation:
`feb.` => `febr.`
Resolves #2917

Use febr. as Hungarian abbreviation for február (February)

---

src/Carbon/CarbonInterface.php
src/Carbon/CarbonInterval.php
src/Carbon/CarbonPeriod.php
src/Carbon/Factory.php
src/Carbon/Traits/Macro.php

Re-enable macro-removal feature from 2.x.

Allow to remove macro by passing null value

---

src/Carbon/Month.php
src/Carbon/WeekDay.php

Use static values for enums until dropping PHP 8.1

---

src/Carbon/List/regions.php

Fix #2956
Note for people needing custom region names: you can still use the previous name or any other and you can more generally choose your own name for any code
```php
$locale = new Language('zh_TW');
$region = match ($locale->getRegion()) {
// Here you can override whatever code
'TW' => 'The name you want for TW in your app',
'US' => 'The name you want for US in your app',
//...
default => $locale->getRegionName(),
};
```
One more note: Carbon and its contributor are not siding neither against nor for the unification and do not intent to give any political opinion on the Taiwan government matter. We genuinely intend to provide an unambiguous and respectful name to locate the ISO code "TW" and to keep it short if possible cutting anything not strictly necessary to serve this purpose. …

Remove unnecessary suffix to Taiwan name

---

src/Carbon/Traits/Creator.php

Hi,
I fixed an incorrect type in `Carbon\Traits\Creator`. Show a warning when I use PHPStan to analyse.

fix incomplete type for create method PHPDoc

---

src/Carbon/AbstractTranslator.php
src/Carbon/CarbonPeriod.php
src/Carbon/Exceptions/BadComparisonUnitException.php
src/Carbon/Exceptions/BadFluentConstructorException.php
src/Carbon/Exceptions/BadFluentSetterException.php
src/Carbon/Exceptions/ImmutableException.php
src/Carbon/Exceptions/InvalidDateException.php
src/Carbon/Exceptions/NotACarbonClassException.php
src/Carbon/Exceptions/NotLocaleAwareException.php
src/Carbon/Exceptions/OutOfRangeException.php
src/Carbon/Exceptions/ParseErrorException.php
src/Carbon/Exceptions/UnitNotConfiguredException.php
src/Carbon/Exceptions/UnknownGetterException.php
src/Carbon/Exceptions/UnknownMethodException.php
src/Carbon/Exceptions/UnknownSetterException.php
src/Carbon/Exceptions/UnknownUnitException.php
src/Carbon/Exceptions/UnsupportedUnitException.php
src/Carbon/Factory.php
src/Carbon/Traits/Date.php
src/Carbon/Traits/Localization.php
src/Carbon/TranslatorImmutable.php
tests/AbstractTestCase.php
tests/Carbon/DiffTest.php
tests/Carbon/Fixtures/NoLocaleTranslator.php
tests/Carbon/MacroTest.php
tests/CarbonImmutable/DiffTest.php
tests/CarbonImmutable/MacroTest.php
tests/CarbonImmutable/TestingAidsTest.php

Fixes all issues that emit deprecation notices on PHP 8.4 for implicit nullable parameter type declarations.
See:
- [RFC](https://wiki.php.net/rfc/deprecate-implicitly-nullable-types)
- [PHP 8.4: Implicitly nullable parameter declarations deprecated](https://php.watch/versions/8.4/implicitly-marking-parameter-type-nullable-deprecated)

[PHP 8.4] Fixes for implicit nullability deprecation

---

src/Carbon/CarbonInterval.php
tests/CarbonInterval/TotalTest.php

Stop using start/end on interval if they are changed after creation

---

src/Carbon/CarbonPeriod.php
src/Carbon/Traits/Converter.php
tests/CarbonPeriod/CreateTest.php

Make start and end period properties correct when created from Carbon object

---

src/Carbon/Traits/IntervalRounding.php
tests/CarbonInterval/ConstructTest.php
tests/CarbonInterval/RoundingTest.php

Hello there!
In [Carbon\Traits\IntervalRounding::45](https://github.com/briannesbitt/Carbon/blob/master/src/Carbon/Traits/IntervalRounding.php#L45), we convert a CarbonInterval to a string, regardless of the language in which it was given. This fails, if:
- the user passes a CarbonInterval in a specific locale
- the user passes an Object, that is converted to a CarbonInterval, while the CarbonLocale is set to a language different than english.
As we are parsing english words, we should ensure in the library, that the passed `unit` is english, regardless of what the user does.
Therefore i suggest always to create a new CarbonInterval, set it's locale to default and parse the output of this object.

Fix: Allow carbon instance to be rounded by a CarbonInterval, which is not in default language

---

src/Carbon/Traits/Test.php
tests/Carbon/TestingAidsTest.php

Fallback to default timezone for mocked now

---

src/Carbon/CarbonPeriod.php

This constant is has the same value as the one of the base class. Overriding this constant breaks in PHP 8.4 due to the addition of the constant type.
See https://github.com/php/php-src/pull/12361 for the discussion. We might end up reverting this, but it still doesn't seem like this constant is needed.
I wasn't sure which branch to target. Please let me know which one is correct and I can rebase.

Remove overridden EXCLUDE_START_DATE constant

---

src/Carbon/CarbonPeriod.php
src/Carbon/Traits/Creator.php
tests/CarbonPeriod/CreateTest.php

Build period with given timezone

---

src/Carbon/Traits/Rounding.php
src/Carbon/Traits/Week.php

Use static instead of CarbonInterface return type in doclocks

---

phpstan.neon
src/Carbon/CarbonInterface.php
src/Carbon/Traits/Boundaries.php
src/Carbon/Traits/Comparison.php
tests/Carbon/IsTest.php
tests/CarbonImmutable/IsTest.php

Implement isStartOf* and isEndOf* for all units

---

src/Carbon/CarbonInterval.php
tests/CarbonInterval/TotalTest.php

Consider absolute flag when comparing intervals

---

src/Carbon/Traits/Date.php

This PR reduces `avoidMutation()` calls.

Optimize `setUnitNoOverflow()`

---

src/Carbon/Traits/Cast.php
src/Carbon/Traits/Converter.php
src/Carbon/Traits/Creator.php
src/Carbon/Traits/Date.php
src/Carbon/Traits/IntervalStep.php
src/Carbon/Traits/Units.php
tests/Carbon/ObjectsTest.php
tests/Carbon/SettersTest.php
tests/CarbonInterval/ConstructTest.php

Prevent loosing offset when same time exist as 2 different offset in the same timezone

Fix timezone issue when add/sub with overflow

---

src/Carbon/Lang/oc.php

Correction for ordinals for year.
In Occitan we have two words for 'year':
un an, x ans etc (masculine)
or
una annada, x annadas etc (feminine)
Here the masculine form was chosen so I changed accordingly the function for ordinals.

Update Occitan locale: small correction

---

src/Carbon/Lang/az.php
tests/Localization/AzAzTest.php
tests/Localization/AzCyrlTest.php
tests/Localization/AzLatnTest.php
tests/Localization/AzTest.php

fix: correct time unit abbreviations and format mismatches for Azerbaijani translation

---

contribute/docs/index.html
contribute/index.html
contribute/translate/index.html
contribute/translators/index.html
docs/index.html
history/index.html
index.html
laravel/index.html
symfony/index.html
template.src.html

Since the link https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css couldn't be accessed in China, I simply replaced it with https://cdn.jsdelivr.net/ altogether.

Modify the CDN of static files

---

docs/index.html

Documentation says `CarbonInterval::days(3.5)` returns `3.0hrs` in Carbon 2, but it actually returns `3.0 days`.
I assume the latter part of this example is where the mistake lies rather than the code itself, as `CarbonInterval::days(3.5)` is used multiple times in the example code block directly beneath it, and it makes sense that these should all match.
I've tried to match the existing documentation convention for units (`days` and `hours`), instead of writing `3d 00h`.
NOTE: This is my first contribution to this repository, please let me know if you need me to adjust anything.
Thanks!

Fix incorrect documentation for CarbonInterval

---

phpstan.neon
src/Carbon/CarbonInterval.php
src/Carbon/Traits/Macro.php

Hey, resolves #3173 using [param-closure-this](https://phpstan.org/writing-php-code/phpdocs-basics#callables).

Fix Incorrect Type Inference when Declaring Macros

---

src/Carbon/Laravel/ServiceProvider.php
tests/Laravel/App.php
tests/Laravel/ServiceProviderTest.php

Not sure if this is a fix or a feature.
This PR applies Laravel's configured fallback locale to Carbon.
Laravel doesn't emit any events while setting fallback locale at run-time, so this is one-time thing during service provider boot up.

feat: Apply Laravel fallback locale
